const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const root=path.resolve(__dirname,'../../../..'),raw=path.join(root,'shared/assets/blank-project-coding/original-restored-v2/raw');fs.mkdirSync(raw,{recursive:true});
const py=path.join(root,'qwen3-tts/.venv/Scripts/python.exe');
const candidates=[['tetris','lt1Lal2gh_E'],['inventory','LD2CFMXoIXM'],['save','wSq1QJ-g91M'],['duck','WahYlxs9Ns0'],['game','GwCiGixlqiU'],['profile','lfuGLaZ3khs']];
function run(args,logfile){return new Promise((resolve,reject)=>{const p=spawn(py,['-X','utf8','-m','yt_dlp','--js-runtimes','node','--no-warnings',...args],{cwd:root,windowsHide:true}),chunks=[];let err='';p.stdout.on('data',d=>{chunks.push(d);if(logfile)fs.appendFileSync(logfile,d)});p.stderr.on('data',d=>{err+=d;if(logfile)fs.appendFileSync(logfile,d)});p.on('exit',c=>c?reject(Error(err.slice(-1500))):resolve(Buffer.concat(chunks).toString('utf8')));p.on('error',reject)});}
(async()=>{let records=[];for(const [key,id]of candidates){const url='https://www.youtube.com/watch?v='+id;const m=JSON.parse(await run(['--skip-download','--dump-single-json',url]));const allowed=/Creative Commons Attribution/i.test(m.license||'')||m.channel_id==='UCxboW7x0jZqFdvMdCFKTMsQ'&&/licensed under the CC-By 4\.0|CC-BY 4\.0 LICENSE/i.test(m.description||'');if(!allowed)throw Error('License not confirmed: '+id);records.push({key,id,url,title:m.title,uploader:m.uploader,channelId:m.channel_id,seconds:m.duration,license:m.license||'CC BY 4.0 in video description',licenseNotice:m.description.split('\n').filter(l=>/licen|attribute|creativecommons|GDQuest and contributors/i.test(l)),chapters:m.chapters||[],checkedAt:new Date().toISOString(),priorUse:key==='tetris'?'ai-era-cs-fundamentals used54–60.5/84–90.5/320–326.5; exclude these intervals':key==='game'?'ai-era-cs-fundamentals used7472–7491.5; exclude interval':key==='profile'?'ai-era-cs-fundamentals used186–205.5; exclude interval':'no matching source found in previous selected-footage history',raw:'shared/assets/blank-project-coding/original-restored-v2/raw/'+key+'.mp4'});}
fs.writeFileSync(path.join(__dirname,'sources.json'),JSON.stringify({checkedAt:new Date().toISOString(),candidates:records,rejected:[{id:'rAUn1Lom6dw',reason:'No explicit video reuse license in returned metadata; tutorial remains a reference, not production footage.'},{id:'8OK8_tHeCIA',reason:'No explicit video reuse license; open source code permission is not video reuse permission.'}],sourceSound:'Retain permitted game sound; mute original speech/music where it competes with narration or introduces third-party music. Continuous approved Nimbus remains.',credits:'CC BY source attribution on the relevant footage; omit public-description credits per user, keep full internal records.'},null,2)+'\n');
console.log('Confirmed6source licenses; metadata and chapters recorded.');
if(process.argv.includes('--metadata-only'))return;
for(const s of records){const dest=path.join(root,s.raw);if(fs.existsSync(dest)){console.log('Reuse downloaded original '+s.key);continue;}if(s.key==='game'){console.log('Game long source needs exact reviewed chapter window; skip full download.');continue;}
await run(['--no-progress','--no-playlist','-f','bv[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4]','--merge-output-format','mp4','-o',dest,s.url],path.join(__dirname,'download.log'));console.log('Downloaded '+s.key);}
})().catch(e=>{console.error(e);process.exitCode=1});
