const fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');const W=__dirname,R=path.resolve(W,'../../../..'),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),plan=read(path.join(W,'plan.json')),m=read(path.join(W,'final.manifest.json')),O=path.join(W,'cuts');
function run(cmd,args){const r=spawnSync(cmd,args,{encoding:'utf8',windowsHide:true,maxBuffer:4e6});if(r.status!==0)throw Error(r.stderr||String(r.error));return r.stdout;}
const ff=a=>run('ffmpeg',['-v','error','-y','-threads','2',...a]);const enc=['-an','-c:v','libx264','-threads','3','-preset','veryfast','-crf','18','-pix_fmt','yuv420p','-r','60','-video_track_timescale','90000'];
const baseline=path.join(W,'baseline/media/blank-project-coding.mp4'),meta=JSON.parse(run('ffprobe',['-v','error','-show_format','-of','json',baseline]));
ff(['-i',baseline,'-frames:v','120',...enc,path.join(O,'intro.mp4')]);ff(['-ss',String(Number(meta.format.duration)-10),'-i',baseline,'-frames:v','600',...enc,path.join(O,'outro.mp4')]);
for(const c of plan.cuts){if(!c.source||!fs.existsSync(path.join(R,c.source)))throw Error('Missing rendered cut '+c.id);const p=JSON.parse(run('ffprobe',['-v','error','-select_streams','v:0','-show_entries','stream=nb_frames,width,height,r_frame_rate','-of','json',path.join(R,c.source)])).streams[0];if(Number(p.nb_frames)!==c.frames||p.width!==1920||p.height!==1080||p.r_frame_rate!=='60/1')throw Error('Cut frame verification '+c.id+' '+JSON.stringify(p));}
const files=[path.join(O,'intro.mp4'),...plan.cuts.map(c=>path.join(R,c.source)),path.join(O,'outro.mp4')];const concat=path.join(W,'final-concat.txt');fs.writeFileSync(concat,files.map(f=>`file '${f.replaceAll('\\','/')}'`).join('\n'));
ff(['-f','concat','-safe','0','-i',concat,'-i',path.join(R,m.paths.audioMix),'-map','0:v:0','-map','1:a:0','-c','copy','-t',String(plan.seconds),'-movflags','+faststart',path.join(R,m.paths.videoClean)]);
fs.writeFileSync(path.join(W,'assembly.json'),JSON.stringify({createdAt:new Date().toISOString(),frames:plan.totalFrames,seconds:plan.seconds,allCutFramesVerified:true,sourceSequence:files.map(f=>path.relative(R,f).replaceAll('\\','/')),originalIntroAndMemberIdentitiesRetained:true,visualQa:'pending',humanListening:'pending'},null,2)+'\n');console.log('Restored original-order narrated clean master assembled.');
