// Promotion gate: run only after direct review of every final cut and caption.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawnSync}=require('child_process');const W=__dirname,R=path.resolve(W,'../../../..'),read=f=>JSON.parse(fs.readFileSync(path.join(W,f),'utf8')),rel=f=>path.relative(R,path.join(W,f)).replaceAll('\\','/');
const q=read('qa.json'),v=read('direct-visual-review.json'),p=read('plan.json'),m=read('final.manifest.json'),a=read('mix-alignment-review.json');
assert(v.allFinalCutPagesDirectlyViewed&&v.allCaptionStripPagesDirectlyViewed&&v.allCompositionPagesDirectlyViewed);assert.equal(v.reviewedCaptionSegments,q.captionSegmentCount);assert.equal(v.captionedSha256,q.videoBurnedCaptions.sha256);assert.equal(v.cleanSha256,q.videoClean.sha256);assert(q.videoClean.fullDecodePassed&&q.videoBurnedCaptions.fullDecodePassed&&a.all56SceneStartsVerified);assert(read('editor-timing-review.json').matches);
q.directVisualReview='every-selected-cut-first-middle-last, final-explanation-compositions and every-burned-caption-segment directly reviewed';q.directVisualReviewEvidence=rel('direct-visual-review.json');fs.writeFileSync(path.join(W,'qa.json'),JSON.stringify(q,null,2)+'\n');
const layouts=read('caption-layout-qa.json');layouts.renderedVisualReview='All current burned caption segments directly viewed; center960,970 and source UI clearance verified';fs.writeFileSync(path.join(W,'caption-layout-qa.json'),JSON.stringify(layouts,null,2)+'\n');
for(const c of p.cuts)c.visualReview='direct-final-cut-and-caption-contact-review-passed';fs.writeFileSync(path.join(W,'plan.json'),JSON.stringify(p,null,2)+'\n');const fc=read('footage-cuts.json');fc.clips=p.cuts;fs.writeFileSync(path.join(W,'footage-cuts.json'),JSON.stringify(fc,null,2)+'\n');
m.status='original-restored-v2-locally-reviewed-private-upload-pending';m.membershipOutro.appliedToFinal=true;m.editing.timingStatus='frame-exact-final-outputs-verified';m.editing.exampleInterleaving.reviewStatus='all-current-final-cuts-and-chapter-connections-directly-reviewed';m.audio.finalMeasurement={integratedLufs:Number(q.mixMeasurement.input_i),truePeakDbtp:Number(q.mixMeasurement.input_tp),source:rel('qa.json')};m.approvals.render='technical-and-direct-visual-QA-passed; full-human-listening-pending';m.approvals.broll='actual-source-cuts-first-middle-last-and-chapter-connections-directly-reviewed';m.production={currentStage:'local-qa-complete-private-upload-pending',ttsGenerated:true,rendered:true,collected:false,uploaded:false};m.duplicateReview={kind:'explicit-original-script-restoration-revision',report:rel('publishing/revision-preflight.json'),status:'previous-version-and-related-published-video-preserved',mustRefreshBeforeProduction:false};m.finalRender.directVisualReview=rel('direct-visual-review.json');m.finalRender.originalPreservationAudit=rel('original-preservation-audit.json');m.finalRender.warningsPreserved=true;
m.editing.channelIntro.status='applied-to-current-final';m.editing.channelIntro.appliedToFinal=true;m.audio.mixStatus='current-original56-scenes-and-continuous-Nimbus-mixed-and-technically-verified';
fs.writeFileSync(path.join(W,'final.manifest.json'),JSON.stringify(m,null,2)+'\n');fs.writeFileSync(path.join(R,'projects/blank-project-coding/project.json'),JSON.stringify(m,null,2)+'\n');
const r=spawnSync(process.execPath,['scripts/collect-video-output.cjs','blank-project-coding'],{cwd:R,encoding:'utf8',windowsHide:true,maxBuffer:6e6});if(r.status!==0)throw Error(r.stderr||r.stdout);console.log(r.stdout);
m.production.collected=true;m.production.currentStage='collected-private-upload-pending';for(const f of [path.join(W,'final.manifest.json'),path.join(R,'projects/blank-project-coding/project.json')])fs.writeFileSync(f,JSON.stringify(m,null,2)+'\n');
const cp=read('checkpoint.json');cp.stage='full-local-output-collected-private-upload-pending';cp.updatedAt=new Date().toISOString();cp.seconds=p.seconds;cp.cues=q.cueCount;cp.remaining=['New private upload with manually uploadedKO/EN tracks and English metadata','Coaching card, final10s links and actual ad checks','Verify burned captions with playerCCoff','Metadata-only Git/rebuild checks, commit and push'];fs.writeFileSync(path.join(W,'checkpoint.json'),JSON.stringify(cp,null,2)+'\n');console.log('Current v2 output collected after final QA; old private upload and baseline retained.');
