"""Sync a project's measured narration timing into its Motion Canvas project.

Usage:
    qwen3-tts/.venv/Scripts/python.exe qwen3-tts/build_project_timing.py \
        --project frame-rate-modern-rendering
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAP_FPS = 30
RENDER_FPS = 60


def repo_path(relative: str) -> Path:
    resolved = (ROOT / relative).resolve()
    resolved.relative_to(ROOT.resolve())
    return resolved


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True)
    args = parser.parse_args()

    manifest_path = ROOT / "projects" / args.project / "project.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("slug") != args.project:
        raise ValueError("Manifest slug does not match --project")

    script_path = repo_path(manifest["paths"]["script"])
    script = json.loads(script_path.read_text(encoding="utf-8"))
    scenes = script["scenes"]

    output_dir = repo_path(manifest["tts"]["outputDir"])
    stem = manifest["tts"]["filenameStem"]
    timing_path = output_dir / f"{stem}.timing.json"
    wav_path = output_dir / f"{stem}.wav"
    timing = json.loads(timing_path.read_text(encoding="utf-8"))

    first_by_scene: dict[str, dict] = {}
    for entry in timing["entries"]:
        first_by_scene.setdefault(str(entry["scene_id"]), entry)

    missing = [scene["id"] for scene in scenes if scene["id"] not in first_by_scene]
    if missing:
        raise KeyError(f"Missing narration timing for scenes: {', '.join(missing)}")

    cut_frames = [round(first_by_scene[scene["id"]]["start"] * SNAP_FPS) for scene in scenes]
    cut_frames.append(round(float(timing["duration_seconds"]) * SNAP_FPS))
    durations = [(cut_frames[i + 1] - cut_frames[i]) / SNAP_FPS for i in range(len(scenes))]
    starts = [frame / SNAP_FPS for frame in cut_frames[:-1]]
    total = cut_frames[-1] / SNAP_FPS

    motion_project = repo_path(manifest["paths"]["motionCanvasProject"])
    motion_dir = motion_project.parent
    timing_ts = motion_dir / "timing.ts"

    lines = [
        "// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.",
        f"export const NARRATION_FPS = {RENDER_FPS};",
        f"export const TOTAL_DURATION = {total};",
        "",
        "export const SCENE_STARTS = [",
        *[f"  {value}," for value in starts],
        "] as const;",
        "",
        "export const SCENE_DURATIONS = [",
        *[f"  {value}," for value in durations],
        "] as const;",
        "",
        "export const SCENE_TITLES = [",
        *[f"  {js_string(scene['title'])}," for scene in scenes],
        "] as const;",
        "",
        f"export const TOTAL_FRAMES = {cut_frames[-1] * (RENDER_FPS // SNAP_FPS)};",
        "",
    ]
    timing_ts.write_text("\n".join(lines), encoding="utf-8")

    audio_target = motion_dir / "assets" / "narration.wav"
    audio_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(wav_path, audio_target)

    manifest["video"]["durationSeconds"] = round(total, 3)
    manifest["status"] = "production"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {timing_ts}")
    print(f"Synced {audio_target}")
    for scene, start, duration in zip(scenes, starts, durations):
        print(f"  {scene['id']} {start:7.3f}s + {duration:6.3f}s  {scene['title']}")
    print(f"Total: {total:.3f}s / {cut_frames[-1] * 2} frames @ 60fps")


if __name__ == "__main__":
    main()
