// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 198.23333333333332;

export const SCENE_STARTS = [
  0.0,
  41.2,
  78.33333333333333,
  113.83333333333333,
  152.46666666666667,
] as const;

export const SCENE_DURATIONS = [
  41.2,
  37.13333333333333,
  35.5,
  38.63333333333333,
  45.766666666666666,
] as const;

export const SCENE_TITLES = [
  "스타트를 누르면, 바로 마리오",
  "모자 하나로 알려 주는 게임",
  "이야기는 짧게, 한복판에서",
  "보는 것이 아니라, 되어 보는 것",
  "튜토리얼도, 제목도 놀이 뒤에",
] as const;

export const TOTAL_FRAMES = 11894;
