// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 212.46666666666667;

export const SCENE_STARTS = [
  0.0,
  45.03333333333333,
  84.86666666666666,
  133.6,
  169.6,
] as const;

export const SCENE_DURATIONS = [
  45.03333333333333,
  39.833333333333336,
  48.733333333333334,
  36.0,
  42.86666666666667,
] as const;

export const SCENE_TITLES = [
  "스타트를 눌렀는데, 아직도 영상",
  "그래서, 무슨 게임인데?",
  "이야기가 꼭 필요하다면",
  "게임만 줄 수 있는 것부터",
  "무엇을 먼저 보여 줄지 정하기",
] as const;

export const TOTAL_FRAMES = 12748;
