// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 222.56666666666666;

export const SCENE_STARTS = [
  0.0,
  23.933333333333334,
  56.333333333333336,
  92.8,
  125.36666666666666,
  157.93333333333334,
  197.93333333333334,
] as const;

export const SCENE_DURATIONS = [
  23.933333333333334,
  32.4,
  36.46666666666667,
  32.56666666666667,
  32.56666666666667,
  40.0,
  24.633333333333333,
] as const;

export const SCENE_TITLES = [
  "버튼은 하나, 판단은 여러 개",
  "연타 — 얼마나 빠르게 누를까",
  "타이밍 — 지금 누르면 맞을까",
  "반응 — 신호가 나오면 눌러라",
  "누르기와 떼기 — 무엇을 받아들일까",
  "입력이 단순할수록, 결과는 선명하게",
  "버튼보다 먼저, 플레이어의 판단을 설계하자",
] as const;

export const TOTAL_FRAMES = 13354;
