// Original lesson; shares approved production assets, never old teaching content.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../..'),slug='responsive-game-feedback',base=path.dirname(__dirname),old=path.join(root,'projects/praise-player');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');};
const ko=[
 ['입력을 받았다는 신호',['에이퍼처 데스크 잡에서는 조작 패널과 버튼 안내가 화면 안에 들어옵니다.','하프라이프 알릭스에서는 집을 수 있는 대상이 손의 움직임과 함께 강조됩니다.','이런 표시가 있더라도, 누른 뒤 아무 변화가 없으면 다른 질문이 생깁니다.','버튼을 못 받은 걸까요, 받았지만 지금 실행할 수 없는 걸까요?','직접 만든 테스트에서 문을 열어 보겠습니다.','두 화면의 문은 똑같이 잠겨 있고, 누른 버튼도 같습니다.','한쪽은 그대로 있고, 다른 쪽은 잠긴 이유를 짧게 알려 줍니다.','입력을 받았다는 응답은, 행동에 성공했다는 칭찬과 구분해야 합니다.']],
 ['거절할 때는 다음 행동의 단서',['이번에는 건물을 놓을 자리를 고르는 테스트입니다.','이미 건물이 있는 곳에 놓으려 하면, 두 화면 모두 건설을 거절합니다.','한쪽은 색만 바뀌고, 다른 쪽은 다른 건물과 겹친다고 알려 줍니다.','빈자리로 옮겨도 재료가 부족하면, 부족한 재료가 표시됩니다.','거절 이유가 달라졌으니, 다음에 해 볼 행동도 달라집니다.','건설 불가라는 한 문구로 모든 상황을 뭉개지 않는 것입니다.','설명은 짧게 두고, 색상과 함께 글자로도 거절 이유를 알려 주세요.','이 테스트의 재료 수와 배치는 설명을 위해 직접 만든 조건입니다.']],
 ['메뉴에서는 확인 의도를 알아보기',['게임을 시작하는 메뉴에서 확인 버튼을 잘못 누를 수도 있습니다.','이번 비교는 한쪽은 엔터만, 다른 쪽은 엔터와 스페이스를 확인으로 받습니다.','두 번째 화면은 받을 수 있는 버튼을 메뉴 옆에 함께 표시합니다.','같은 확인 의도로 쓰기 쉬운 버튼을 연결해 보는 방법입니다.','하지만 뒤로 가기나 삭제처럼 결과가 다른 버튼까지 섞어서는 안 됩니다.','여러 버튼을 받는 것이 항상 정답이라는 뜻도 아닙니다.','우리 게임의 조작 약속과 충돌하는지 먼저 살펴보세요.','확인할 수 있는 방법을 알아보고, 누른 뒤의 상태도 이어서 보여 줍니다.']],
 ['컷신은 응답과 확정을 나누기',['컷신을 건너뛰려고 버튼을 눌렀는데 아무 반응이 없을 때도 있습니다.','이 테스트는 짧게 누르면 건너뛰기 안내를 보여 줍니다.','길게 누르면 표시가 차오르고, 끝까지 채웠을 때 컷신을 넘깁니다.','실수로 한 번 눌렀다고 장면 전체가 사라지지 않게 하는 선택입니다.','누른 뜻을 알아봤다는 신호와, 정말 건너뛰겠다는 확정을 나누는 거죠.','버튼을 중간에 놓으면 확인이 취소되고 장면은 계속됩니다.','모든 컷신에 길게 누르기를 강제할 필요는 없습니다.','응답이 없어서 다시 누르는 상황과, 기다려야 하는 상황을 구분해 보세요.']],
 ['처리 중을 완료처럼 말하지 않기',['저장처럼 결과가 바로 끝나지 않는 동작도 있습니다.','이 테스트에서는 요청을 받으면 저장 중이라는 상태를 먼저 보여 줍니다.','아직 끝나지 않았으므로 저장 완료라고 표시하지 않습니다.','처리 중에 다시 눌러도 새 요청을 계속 쌓지 않고, 진행 중이라고 알려 줍니다.','완료 상태가 확인된 뒤에만 문구를 바꿉니다.','실제 저장 기능을 구현한 게임이라면 실패했을 때의 응답도 필요합니다.','여기서는 대기 시간을 둔 모의 작업으로 상태 전환을 비교합니다.','입력 수신, 처리 중, 완료를 구분하면 기다림의 의미를 설명할 수 있습니다.']],
 ['필요한 곳에만 응답하기',['모든 키마다 소리와 문구를 띄우면 화면은 금방 시끄러워집니다.','이 테스트는 게임 중에는 상호작용 버튼에, 메뉴에서는 확인 버튼에 응답합니다.','현재 상태에서 의미가 없는 키에는 큰 경고를 붙이지 않습니다.','실행할 수 있을 것처럼 보이는 행동이 막혔을 때, 이유를 우선 보여 주는 것입니다.','버튼은 받았는지, 왜 실행할 수 없는지, 다음에 무엇을 해 볼지 살펴보세요.','응답의 목적은 아무 행동이나 성공시키는 데 있지 않습니다.','성공과 거절과 대기를 알아볼 수 있게 만드는 데 있습니다.','우리 게임에서도 아무 일도 없었다고 느끼는 순간부터 찾아보세요.']]
];
const en=[
 ['Acknowledge the input',['Aperture Desk Job puts a control panel and button prompts inside the scene.','Half-Life: Alyx highlights objects you can pick up as the hand moves.','Even with these cues, a press followed by no visible change raises another question.','Was the input missed, or received but unavailable in this state?','Let us try to open a door in an original test.','Both doors are locked, and both panels receive the same button press.','One stays silent; the other briefly explains why the door is locked.','Acknowledging an input is different from praising a successful action.']],
 ['Explain why an action is unavailable',['This test lets us choose a spot for a building.','Both panels refuse to build on a space that is already occupied.','One changes color; the other also explains that another building is in the way.','On an empty space, insufficient materials produce a different message.','A different reason suggests a different next action.','We avoid using one vague unavailable label for every condition.','Keep the explanation brief and state the reason in words as well as color.','The quantities and layout in this test are original teaching conditions.']],
 ['Recognize confirmation intent in menus',['A player might press a different confirmation key in the start menu.','One panel accepts Enter; the other accepts Enter and Space.','The second panel displays the keys it accepts beside the menu.','This explores mapping familiar confirmation keys to the same intention.','Do not mix in buttons whose results differ, such as Back or Delete.','Accepting more keys is not always the right choice.','First check for conflicts with your game’s control conventions.','Make the accepted input clear, then show the resulting state.']],
 ['Separate acknowledgment from commitment',['A press intended to skip a cutscene can also seem to do nothing.','In this test, a short press reveals the skip prompt.','Holding the button fills an indicator; only a full hold skips the scene.','This choice protects against losing the entire scene after one accidental tap.','The game acknowledges the intention before asking for commitment.','Release the button early to cancel confirmation while the scene continues.','A hold is not required for every cutscene.','Distinguish an apparently missed press from a press that requires a wait.']],
 ['Pending is not complete',['Some actions, such as saving, do not finish immediately.','This test first displays Saving when it receives a request.','It does not say Saved while the operation is still pending.','Another press during processing reports progress instead of queuing more requests.','The label changes only after completion is confirmed.','A game with real persistence also needs a response when saving fails.','Here, a simulated delayed operation illustrates the state transitions.','Received, pending, and complete explain what the wait means.']],
 ['Respond where it matters',['A message and sound for every key can quickly clutter the screen.','This test responds to interaction during play and to confirmation in a menu.','It does not attach a large warning to keys with no meaning in the current state.','Prioritize reasons when an action that appears available is blocked.','Check whether the input arrived, why the action is unavailable, and what to try next.','A response does not need to make every attempted action succeed.','It should make success, refusal, and waiting understandable.','Start with moments in your game where a player feels that nothing happened.']]
];
for(const [lang,rows] of [['ko',ko],['en',en]])write(path.join(base,'script',`narration.${lang}.json`),{title:read(path.join(base,'project.json')).titles[lang],scenes:rows.map(([title,lines],i)=>({id:String(i+1).padStart(2,'0'),title,lines}))});
const m=read(path.join(base,'project.json')),prior=read(path.join(old,'project.json'));
m.membershipOutro=JSON.parse(JSON.stringify(prior.membershipOutro).replaceAll('praise-player',slug));m.membershipOutro.appliedToFinal=false;
m.audio=JSON.parse(JSON.stringify(prior.audio));m.audio.mixStatus='approved-assets-awaiting-new-narration-and-timing';m.audio.musicFallbackGames=['Aperture Desk Job','Half-Life: Alyx'];m.audio.musicFallbackScenes=[];
m.channelIntro={...prior.channelIntro,appliedToFinal:false};m.batch={...prior.batch,sourceIndex:12};m.reference={url:'https://www.youtube.com/watch?v=eia2IAmvtKI',kind:'concept-research-only',scriptVerbatimReuse:false,sourceVideoOrAudioReuse:false};
m.approvals={script:'original six-chapter bilingual lesson under authorized batch production; distinct semantic/actual Studio preflight passed before creation',voiceSample:'same approved Qwen3-TTS 1.7B/ref-text voice reused',bgm:'existing continuous Nimbus authorized for batch',final:'pending actual narrated render and all technical/visual review',publication:'private only; public release belongs to user'};
m.publishReady=false;m.warnings=prior.warnings.filter(s=>!s.startsWith('Nintendo')).concat('Valve policy reviewed; exact footage use and final public rights judgment remain pending.');
Object.assign(m.paths,{editorAudioMix:`motion-canvas/src/projects/${slug}/assets/final-mix.wav`,timeline:`projects/${slug}/production/final-v1/plan.json`,footageCuts:`projects/${slug}/sources/selected-footage.json`,footageManifest:`projects/${slug}/sources/selected-footage.json`,captionEditable:`projects/${slug}/production/final-v1/captions.ko.ass`});
m.editing.gameSelection={review:`projects/${slug}/sources/game-candidates.json`,titles:['Aperture Desk Job','Half-Life: Alyx'],priorUseChecked:true,status:'fresh official source footage reviewed; final exact-cut/public rights review pending'};
m.editing.prototypeComparison='Original door, build grid, menu, cutscene hold, simulated delayed save and context tests; actual keyboard events and resulting state recorded. No previous defense game or footage reused.';write(path.join(base,'project.json'),m);
const policy='https://store.steampowered.com/video_policy?l=dutch';
const chosen=[{game:'Aperture Desk Job',sourceId:'mVDFJRM6F9k',file:`shared/assets/${slug}/raw/desk-job-official.mp4`,candidateIntervals:[[4,9]],fit:'Visible in-world controller panel and button diagram. No claim of pressed-but-rejected input or undisclosed internal input mapping.'},{game:'Half-Life: Alyx',sourceId:'LTLotwKpLgk',file:`shared/assets/${slug}/raw/alyx-official.mp4`,candidateIntervals:[[125,133]],fit:'Hand, selectable highlighted object, gravity-glove pickup at normal speed. Source demonstrates target cues, not input failure or a universal timing rule.'}].map(s=>({...s,url:`https://www.youtube.com/watch?v=${s.sourceId}`,uploader:'Valve',sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,s.file))).digest('hex'),priorUse:{scope:'rg across all project JSON/MD and batch sources on 2026-10-01',result:'No previous use of either game title/source ID; Portal itself was used earlier but this is a new title and recording.'},rights:{policy,checkedAt:'2026-10-01',owner:'Valve',conditions:['Valve game content in free instruction/commentary videos; YouTube Partner Program monetization permitted.','No paid access or licensing of the video, no extraction/distribution of standalone game assets.','Only official Valve recording excerpts; no third-party playthrough.','Original narration and controlled comparisons; no source voice or soundtrack.'],status:'policy-reviewed; exact-use/public-review-pending'}}));
write(path.join(base,'sources/game-candidates.json'),{schemaVersion:1,reviewedAt:new Date().toISOString(),slug,concept:'received, unavailable, awaiting confirmation, pending: distinguish response from success',chosen,rejected:[{game:'Factorio',reason:'Good red/green build-state fit; press-kit requests a public game link and valid-user condition is not established here. Not selected under current no-public-credit workflow.',policy:'https://factorio.com/support/press-kit'},{game:'Satisfactory',reason:'Build clearance fits, but a primary recording/monetization permission for the proposed source was not established. Do not infer permission from wiki or fan archive.'},{game:'Hades',reason:'Publisher requests a public product link, also repeatedly reviewed recently; prefer new compliant candidates.',policy:'https://www.supergiantgames.com/blog/policy-on-lets-play-videos/'},{game:'Dota 2 / Artifact / Dota Underlords',reason:'Candidates not selected: official readily available footage did not establish the desired received/unavailable UI. Third-party recordings are not covered solely by Valve policy.'},{game:'Nintendo Switch Sports / Ring Fit Adventure / Mega Man 11 / Monster Hunter Rise / Mario / Celeste / Kirby / Forza',reason:'Recent recordings or frequently used examples; no automatic source/cut reuse.'}],originalPlaytest:{name:'Input State Workshop',modes:['receipt','blocked','menu','cutscene','pending','context'],humanUsabilityReview:'pending',persistence:'pending mode is explicitly a simulation, not a claim of real disk save'},sourceSpeed:'normal, no loops or artificial slow-down',finalCutReview:'pending measured narration'});
write(path.join(base,'sources/SOURCES.md'),`# Internal sources and rights\n\nResearch-only original concept: https://www.youtube.com/watch?v=eia2IAmvtKI . No original script, audio or video copied.\n\nFresh official Valve sources: Aperture Desk Job mVDFJRM6F9k (4–9s provisional), Half-Life: Alyx LTLotwKpLgk (125–133s provisional). Direct contact-frame review confirms control prompts and object highlighting/pickup respectively; these do not prove invisible button receipt or refusal. The unavailable/menu/cutscene/pending claims use independently coded actual-input tests.\n\nValve Video Policy checked 2026-10-01: https://store.steampowered.com/video_policy?l=dutch . Free instructional/commentary video and YouTube partner monetization permitted; paid access/sale/licensing and standalone extraction prohibited. Third-party works still require their own permission. Both recording owners are Valve; voice/music omitted. Specific final use and public rights decision remain pending. No public credits block per user; internal record retained.\n\nContinuous approved Nimbus restoration, original cat intro and membership identity image reused by user authorization. Original Audio Library file, human listening, truncated member handles and external media backup remain unresolved.\n`);
write(path.join(base,'planning/outline.md'),'# 입력에 응답하기\n\n시청자 질문: 눌렀지만 실행할 수 없는 상태에서 입력 수신·거절·확인 대기를 어떻게 알아보게 할까?\n\n1. 실제 게임의 조작/대상 표시 → 잠긴 문 응답 비교\n2. 건설 거절: 점유와 재료 부족은 다른 이유\n3. 메뉴의 확인 의도와 조작 약속\n4. 컷신 짧은 입력/길게 확인/중간 취소\n5. 모의 저장 요청/진행 중/완료를 분리\n6. 현재 맥락에 의미 있는 응답만\n\n칭찬·프레임/입력 지연·튜토리얼을 반복하지 않는다. 새 게임의 관찰 가능한 표시만 설명한다. 자체 테스트는 실제 키 이벤트와 조건별 상태를 기록하고 인간의 재미/사용성 검증을 추정하지 않는다.\n');
write(path.join(base,'README.md'),'# 버튼 눌렀는데 무반응?\n\n현재 독립 한영 6장 대본과 새 자료 선택을 완료했다. 실제 내레이션·렌더·QA·수집·비공개 업로드는 아직 완료하지 않았다.\n\n사전 중복 검토: production/batches/sakurai-planning-game-design/preflight/responsive-game-feedback.json. 기존 전체 관련 대본과 실제 Studio 반응/피드백 검색 기록을 대조해 distinct. 본편은 실제 게임/개발 테스트60%, 흰2.5D40% 목표. 승인된 목소리와 Nimbus, 2초 고양이 인트로, 10초 원본 회원 엔딩.\n\n공개는 사용자 판단. 인간 청취·게시 권리·원래 Nimbus 파일·회원 잘린 핸들·외부 백업 미완료 경고 유지.\n');
const qf=path.join(root,'production/batches/sakurai-planning-game-design/queue.json'),q=read(qf),item=q.items.find(x=>x.slug===slug);item.status='in-progress';item.stage='original-bilingual-script-and-fresh-official-sources';item.project=`projects/${slug}/project.json`;item.freshGameReview={titles:chosen.map(g=>g.game),manifest:`projects/${slug}/sources/game-candidates.json`,rejected:['Factorio','Satisfactory','Hades','recent game footage']};item.nextAction='Start one approved-voice synthesis and current-hash CPU ASR; build six fresh actual menu/cutscene/blocked/pending input tests and original 2.5D explanations.';item.activeExecution={};item.updatedAt=q.updatedAt=new Date().toISOString();write(qf,q);
console.log('Original 6x8 bilingual lesson configured; no render/upload completion claimed.');
