const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=path.dirname(__dirname),root=path.resolve(__dirname,'../../..'),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');
const policy='https://www.nintendo.co.jp/networkservice_guideline/en/index.html';
const chosen=[
 {game:'Nintendo Switch Sports',sourceId:'tiwjvBSS_Wk',url:'https://www.youtube.com/watch?v=tiwjvBSS_Wk',uploader:'Nintendo of America',file:'shared/assets/praise-player/raw/switch-sports-official.mp4',fit:'Actual Win banner and celebrating avatar after badminton wins. Bowling candidate showed fallen pins but not a strike label and was rejected; scene01 wording is corrected before acceptance.',preview:'projects/praise-player/production/source-win-review.jpg',candidateIntervals:[[237,242],[244,247.5]],muteSourceAudio:true},
 {game:'Ring Fit Adventure',sourceId:'skBNiJd61Qw',url:'https://www.youtube.com/watch?v=skBNiJd61Qw',uploader:'Nintendo of America',file:'shared/assets/praise-player/raw/ringfit-official.mp4',fit:'Actual Nice and Great acknowledgment and movement following success; original prototype parameters are separate. Earlier hold/return-only instructions and later logo/package montage excluded.',preview:'projects/praise-player/production/source-ringfit-final-candidate.jpg',candidateIntervals:[[442,452.5]],muteSourceAudio:true}
];
for(const g of chosen){g.priorUse={checkedAt:new Date().toISOString(),command:'rg Ring Fit|링피트|Switch Sports|스위치 스포츠 in all project JSON/MD, excluding rebuild/raw artifacts',result:'No previous title or recording found in the complete project/source history.'};g.sha256=sha(g.file);g.rights={recordingOwner:g.uploader,policy,checkedAt:'2026-10-01',policyVersion:'2024-09-02',conditions:['Original educational commentary and new comparisons; no trailer republication.','Official Nintendo promotional material is an allowed source category.','YouTube Partner Program monetization; no paid-access game video.','No Nintendo affiliation or sponsorship claim.','Policy applies to individual consumers, not corporate entities; final public rights review remains pending.','External source audio/voice/music omitted; approved Nimbus under commentary.'],status:'policy-reviewed-specific-public-use-review-pending'};}
const rejected=[
 {game:'Devil May Cry 5',sources:['8tmhE2qhTSc','L3EDso2hsWQ','EJ0ACvCgQtc'],reason:'V Combat trailer has no readable style meter. Long official show cases require age authentication and the Capcom policy also excludes unauthorized event republication. No restricted cookies/export/bypass performed; downloaded V trailer is retained locally but excluded.',priorUse:'no repository use found',policy:'https://www.capcomusa.com/video-policy/'},
 {game:'Trackmania',sourceId:'0-p3GeyksAs',reason:'Downloaded official trailer shows tracks but not readable personal-best/medal recognition at the selected moments. Topic fit insufficient; excluded without stretching or inventing an event.',policy:'https://www.ubisoft.com/legal/documents/VideoPolicy/en-INTL/.html'},
 {game:'Rocket League',reason:'Good action callouts, but the Epic fan policy requires a specific disclaimer in connection with the video; prefer a simpler compliant new source for this lesson.',policy:'https://legal.epicgames.com/epicgames/fan-art-policy'},
 {game:'Hades',reason:'Already reviewed in prior production; publisher credit condition and recent-candidate repetition make other sources preferable.'},
 {game:'Hi-Fi Rush',reason:'Ownership-specific recording conditions were not established; do not infer permission from an old general publisher policy.'},
 {game:'Mario/Celeste/Kirby/Forza',reason:'Recent channel/reference examples; not automatically recycle their clips for a fresh topic.'}
];
fs.mkdirSync(path.join(base,'sources'),{recursive:true});fs.writeFileSync(path.join(base,'sources/game-candidates.json'),JSON.stringify({schemaVersion:1,reviewedAt:new Date().toISOString(),slug:'praise-player',concept:'recognize actual success with equal reward/outcome rules',historyScope:'all existing projects/source records and recent three batch videos',chosen,rejected,originalPlaytest:{name:'Praise Defense Lab',gameRulesEqualAcrossPanels:true,comparisons:['timing','specificity','strength','honesty','placement'],humanEnjoymentReview:'pending actual human test'},sourceSpeed:'normal; no loops/slow-down',finalCutReview:'pending final exact intervals'},null,2)+'\n');
fs.writeFileSync(path.join(base,'sources/SOURCES.md'),'# Internal source and rights record\n\nResearch-only source: https://www.youtube.com/watch?v=fryDyXROp8A . No transcript, narration or source video reused.\n\nSelected new game sources: Nintendo of America, Switch Sports tiwjvBSS_Wk and Ring Fit Adventure skBNiJd61Qw. Official gameplay portions will accompany independently authored educational commentary and prototype comparisons, at normal speed. External soundtrack/voice is omitted. No event recording or third-party playthrough selected.\n\nNintendo policy checked 2026-10-01: '+policy+' . Individual-consumer scope, creative commentary, official promotional sources, YouTube Partner Program and no paid game-video access/affiliation are recorded in game-candidates.json. Specific public use and account/entity eligibility remain pending review; automatic copyright checks cannot establish permission.\n\nOriginal Praise Defense Lab is independently coded with actual browser keyboard input, projectile collision and equal paired states. It is a controlled technical demonstration; enjoyment is not proven by automated outcomes.\n\nApproved continuous Nimbus is the existing documented restoration. Original Audio Library bytes remain unverified. Original member rows may show truncated handles; they are not guessed. External storage and human final listening remain pending. Public description has no credits block per user; internal records remain here.\n');
console.log('2 new official sources recorded; unsuitable candidates preserved as excluded.');
