// Record only a real, current pixel review. Human listening remains pending.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../..'),slug=process.argv[2],base=path.join(root,'projects',slug);
if(!['game-math-polar-2d','game-math-polar-3d'].includes(slug)||!process.argv.includes('--visual-reviewed'))throw Error('Use a known lecture slug and --visual-reviewed after reviewing every current cue');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');
const qpath=path.join(base,'production/qa.json'),qa=read(qpath),mfile=path.join(base,'project.json'),m=read(mfile),timeline=read(path.join(base,'production/timeline.json'));
const review=read(path.join(base,'production/pixel-review.json'));
if(!qa.fullDecodePassed||qa.ratioErrorFrames!==0||qa.captionCount!==review.captionCuesChecked||review.status!=='passed'||review.videoSha256!==qa.videos.videoBurnedCaptions.sha256)throw Error('Current whole-video and pixel QA is incomplete');
if(qa.frames!==timeline.frames||qa.actualFrames*5!==qa.bodyFrames*2||qa.explanationFrames*5!==qa.bodyFrames*3)throw Error('Exact frame-based 40:60 failed');
for(const v of Object.values(qa.videos))if(sha(v.path)!==v.sha256)throw Error('Rendered video changed after QA');
for(const image of review.images)if(sha(image.path)!==image.sha256)throw Error('Reviewed image changed');
if(qa.backgroundMusic!==false||qa.narrationOnlyMix.backgroundMusic!==false||qa.narrationOnlyMix.audioInputs.length!==1||!qa.narrationOnlyMix.brandingOutroSilenceVerified)throw Error('No-music narration-only mix evidence missing');
const alignment=read(path.join(root,m.tts.outputDir,m.tts.filenameStem+'.alignment-review.json'));
if(alignment.length!==timeline.scenes.length||alignment.some(s=>s.matchingCharacterCoverage<.93||sha(`${m.tts.outputDir}/chunks/${s.scene}-scene.wav`)!==s.wavSha256))throw Error('ASR alignment does not match every current scene');
const narration=read(path.join(base,'production/narration-review.json'));
if(narration.status!=='passed-agent-script-and-ASR-difference-review'||narration.humanListening!=='pending'||narration.scenes.length!==timeline.scenes.length)throw Error('Meaning/number read-back review is incomplete');
qa.directVisualReview=review;write(qpath,qa);const cpath=path.join(base,'production/caption-layout.json'),captions=read(cpath);captions.pixelReview=review;write(cpath,captions);
m.status='full-lecture-ready-for-private-review';m.membershipOutro.appliedToFinal=true;m.audio.mixStatus='narration-only-rendered-measured-human-listening-pending';m.audio.musicFallbackScenes=[];
m.editing.exampleInterleaving.reviewStatus='passed-source-interval-and-action-to-explanation-review';m.editing.timingStatus=`final-render-verified-${qa.frames}-frames`;
m.delivery.qa=`projects/${slug}/production/qa.json`;m.approvals.visualPixelReview='passed';m.approvals.humanListening='pending';m.publishReady=false;
m.finalRender={status:'local-review-full-lecture-rendered',durationSeconds:qa.seconds,fps:60,qa:m.delivery.qa,renderer:'Manim Community0.20.1/Cairo, FFmpeg composition',backgroundMusic:false,openItems:['사람의 전체 청취 승인 대기','공개 전 게임IP 권리 검토 대기','회원 원본의 잘린 표시명 확인 대기']};write(mfile,m);
const qfile=path.join(__dirname,'queue.json'),queue=read(qfile),item=queue.items.find(x=>x.slug===slug);Object.assign(item,{status:'rendered-and-qa-passed',rendered:true,durationSeconds:qa.seconds,captionCues:qa.captionCount,backgroundMusic:false,pixelQa:true,asrQa:true,humanListening:false});write(qfile,queue);
console.log('Current full lecture render and direct pixel review recorded:',slug,qa.seconds,'seconds');
