// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 375.76666666666665;

export const SCENE_STARTS = [
  0.0,
  43.6,
  88.06666666666666,
  135.2,
  182.46666666666667,
  233.83333333333334,
  280.8666666666667,
  324.4,
] as const;

export const SCENE_DURATIONS = [
  43.6,
  44.46666666666667,
  47.13333333333333,
  47.266666666666666,
  51.36666666666667,
  47.03333333333333,
  43.53333333333333,
  51.36666666666667,
] as const;

export const SCENE_TITLES = [
  "끝내려는데, 딱 조금이 남았다",
  "갖고 싶어야, 보상이다",
  "현재값과 목표를 함께 보여주기",
  "얻었으면, 달라져야 한다",
  "경험치 바가 다음 선택으로 이어질 때",
  "모든 보상을 화면에 붙일 필요는 없다",
  "하나 남았다고, 한 번이면 끝일까?",
  "보상은 다음 플레이를 위한 약속",
] as const;

export const TOTAL_FRAMES = 22546;
