// GENERATED by qwen3-tts/build_motion_canvas_timing.py -- do not edit by hand.
//
// Cut points come from the rendered narration's measured per-line timings
// (shared/output/narration/qwen3-balanced/*.timing.json), snapped to the
// 60 fps render grid. Each scene below runs for exactly `duration`
// seconds, so scene N starts on the same frame the narrator begins the
// matching sentence.

export type NarrationSegment = {
  /** Scene module name under src/scenes/narrated/. */
  key: string;
  /** Human-readable segment name (Korean). */
  label: string;
  /** Absolute start time in the narration audio, in seconds. */
  start: number;
  /** Absolute end time in the narration audio, in seconds. */
  end: number;
  /** Exact scene length in seconds (end - start). */
  duration: number;
  /** Exact scene length in whole frames at NARRATION_FPS. */
  frames: number;
  /** First narrated sentence of this segment, for reference. */
  firstLine: string;
};

export const NARRATION_FPS = 60;
export const NARRATION_TOTAL_SECONDS = 373.3333333333333;
export const NARRATION_TOTAL_FRAMES = 22400;

export const SEGMENTS = {
  intro: {
    key: "intro",
    label: "도입 — 점프가 결정하는 것",
    start: 0.0,
    end: 41.9,
    duration: 41.9,
    frames: 2514,
    firstLine: "게임에서 점프는 가장 익숙한 버튼 하나로 이루어지는 행동입니다.",
  },
  basic: {
    key: "basic",
    label: "프레임마다 더해지는 중력 + 최고점과 낙하",
    start: 41.9,
    end: 84.53333333333333,
    duration: 42.63333333333333,
    frames: 2558,
    firstLine: "게임에서는 캐릭터가 공중에 있는 동안, 매 프레임 일정한 중력을 적용하는 경우가 많습니다.",
  },
  axes: {
    key: "axes",
    label: "가로 이동(X축)과 설계 목표",
    start: 84.53333333333333,
    end: 105.93333333333334,
    duration: 21.4,
    frames: 1284,
    firstLine: "지금까지의 설명은 Y축, 즉 세로 방향 움직임에 관한 것입니다.",
  },
  mario: {
    key: "mario",
    label: "슈퍼 마리오브라더스",
    start: 105.93333333333334,
    end: 128.03333333333333,
    duration: 22.1,
    frames: 1326,
    firstLine: "슈퍼 마리오브라더스의 점프를 보면 상승 속도는 비교적 느립니다.",
  },
  metroid: {
    key: "metroid",
    label: "메트로이드",
    start: 128.03333333333333,
    end: 146.96666666666667,
    duration: 18.933333333333334,
    frames: 1136,
    firstLine: "메트로이드의 점프도 상승 속도가 상당히 느립니다.",
  },
  ghosts: {
    key: "ghosts",
    label: "마계촌",
    start: 146.96666666666667,
    end: 170.86666666666667,
    duration: 23.9,
    frames: 1434,
    firstLine: "반면 마계촌은 비교적 낮은 점프를 사용하고, 공중에서는 좌우 이동이 거의 불가능합니다.",
  },
  sf2: {
    key: "sf2",
    label: "스트리트 파이터 II — 장기에프",
    start: 170.86666666666667,
    end: 194.23333333333332,
    duration: 23.366666666666667,
    frames: 1402,
    firstLine: "스트리트 파이터 II의 장기에프 스크류 파일드라이버를 보겠습니다.",
  },
  smashSquat: {
    key: "smashSquat",
    label: "스매시브라더스 — 점프 스쿼트",
    start: 194.23333333333332,
    end: 220.1,
    duration: 25.866666666666667,
    frames: 1552,
    firstLine: "대난투 스매시브라더스에는 점프하기 직전, 아주 짧은 준비 동작인 점프 스쿼트가 들어갑니다.",
  },
  smashUltimate: {
    key: "smashUltimate",
    label: "스매시브라더스 얼티밋 — 초기 가속",
    start: 220.1,
    end: 254.66666666666666,
    duration: 34.56666666666667,
    frames: 2074,
    firstLine: "스매시브라더스를 만들 때마다, 점프가 꼭 지금과 같은 방식이어야 하는지 다시 고민하게 됩니다.",
  },
  jumpKing: {
    key: "jumpKing",
    label: "점프킹 — 차지 후 발사",
    start: 254.66666666666666,
    end: 282.0,
    duration: 27.333333333333332,
    frames: 1640,
    firstLine: "이번엔 비교적 최근 게임 중에서, 점프를 아예 다르게 다루는 사례를 몇 가지 더 보겠습니다.",
  },
  celeste: {
    key: "celeste",
    label: "셀레스트 — 홀드 길이로 조절",
    start: 282.0,
    end: 310.1,
    duration: 28.1,
    frames: 1686,
    firstLine: "셀레스트는 정반대의 방법으로 정밀한 조절을 만들어냅니다.",
  },
  megaman: {
    key: "megaman",
    label: "록맨 X — 대시 점프",
    start: 310.1,
    end: 337.1666666666667,
    duration: 27.066666666666666,
    frames: 1624,
    firstLine: "록맨 X의 대시 점프는 세로와 가로 움직임을 완전히 분리해서 얻는 효과를 보여줍니다.",
  },
  outro: {
    key: "outro",
    label: "결론 — 정답은 없다",
    start: 337.1666666666667,
    end: 373.3333333333333,
    duration: 36.166666666666664,
    frames: 2170,
    firstLine: "그렇다면 재밌는 점프에는 하나의 정답이 있을까요? 꼭 그렇지는 않습니다.",
  },
} satisfies Record<string, NarrationSegment>;

/** Scene order, matching the narration audio. */
export const SEGMENT_ORDER = ['intro', 'basic', 'axes', 'mario', 'metroid', 'ghosts', 'sf2', 'smashSquat', 'smashUltimate', 'jumpKing', 'celeste', 'megaman', 'outro'] as const;
