// Record real source edits, compiled C++ and playable tests at current voice times.
// This controls only the project's owned localhost app. No external account UI.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{spawnSync}=require('child_process'),puppeteer=require('../../../motion-canvas/node_modules/puppeteer');
const root=path.resolve(__dirname,'../../..'),work=path.join(__dirname,'final-v1'),planPath=process.env.BLANK_PLAN_FILE?path.resolve(root,process.env.BLANK_PLAN_FILE):path.join(work,'plan.json'),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),plan=read(planPath),catalog=require('../examples/lessons.cjs'),reportFile=path.join(work,'capture-final.json');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),rel=p=>path.relative(root,p).replaceAll('\\','/'),wait=ms=>new Promise(r=>setTimeout(r,Math.max(0,ms)));
const src=path.join(root,'shared/assets/blank-project-coding/voice-timed-v1'),cuts=path.join(root,'shared/assets/blank-project-coding/final-cuts');fs.mkdirSync(src,{recursive:true});fs.mkdirSync(cuts,{recursive:true});
const inputs=['app.js','engine.js','style.css','index.html','lessons.cjs','server.cjs','trace.hpp'].map(f=>({path:'projects/blank-project-coding/examples/'+f,sha256:hash(path.join(__dirname,'../examples',f))}));
const a=(kind,arg,f=0)=>({kind,arg,f}),full=(f=0)=>a('full',null,f),source=(v,f=0)=>a('source',v,f),type=(v,f=0)=>a('type',v,f),run=(f=0)=>a('run',null,f),step=(f=0)=>a('step',null,f),blank=(f=0)=>a('blank',null,f),input=(v,f=0)=>a('input',v,f),scenario=(v,f=0)=>a('scenario',v,f),scroll=(v,f=0)=>a('scroll',v,f),debug=(f=0)=>a('debug',null,f),note=(v,f=0)=>a('note',v,f);
const schedules={
 '01':[[full(),scenario('two-rows',.1),input('down',.28),input('drop',.46),input('rotate',.75)],[full(),blank(.15)],[type('data',.05),run(.8)],[full(),input('right',.16),input('down',.37),input('rotate',.58),input('drop',.8)]],
 '03':[[source('pair'),scroll('struct Node',.4)],[run(),step(.32),scroll('head->next',.55)],[step(),step(.4),step(.7)],[run(),step(.2),step(.4),step(.6),step(.82)]],
 '05':[[source('pair'),scroll('Node* next',.2)],[blank(.12)],[type('node',.18)],[run(),step(.45),step(.8)]],
 '07':[[blank(),type('pair',.06)],[run(),step(.33),scroll('for (',.63)],[step(),step(.45)],[step(),step(.5)]],
 '09':[[source('insert'),run(.08),step(.35),step(.62)],[scroll('Node* added',.1)],[run(),step(.2),scroll('head->next = added',.36),step(.62)],[step(),step(.7)]],
 '10':[[source('remove'),run(.04),step(.58)],[step(.08),step(.64)],[step(.13),step(.72)],[run(),step(.25),step(.45),step(.64),step(.79),step(.9)]],
 '12':[[source('movement'),run(.05),full(.16),input('right',.28),input('rotate',.43),scenario('two-rows',.58),input('drop',.76)],[full(),blank(.2)],[type('data',.2)],[run(),input('right',.26),input('left',.55)]],
 '14':[[blank(),type('data',.05),run(.79)],[input('right',.12),input('right',.46),input('left',.76)],[scroll('const position'),input('down',.3),input('right',.65)],[input('left',.06),input('right',.28),input('left',.51),input('down',.72)]],
 '16':[[full(),scenario('right-wall',.06),input('right',.24),scenario('occupied',.45),input('down',.7)],[scenario('right-wall'),input('right',.2),input('right',.55)],[scenario('empty'),input('right',.2),scenario('left-wall',.48),input('left',.69)],[scenario('occupied'),input('down',.13),input('down',.26),input('down',.39),input('down',.53),input('down',.66),input('down',.8)]],
 '18':[[source('rotation'),run(.02),full(.13),input('rotate',.26),scenario('right-wall',.49),input('rotate',.7)],[scenario('right-wall'),input('rotate',.2),input('right',.42),input('rotate',.7)],[full(),scroll('return turned'),full(.6),scenario('occupied',.75)],[input('rotate',.04),input('down',.2),input('rotate',.4),scenario('right-wall',.6),input('rotate',.8)]],
 '19':[[full(),scenario('one-row',.02),input('down',.3),input('drop',.66)],[scenario('two-rows'),input('down',.28),input('drop',.57)],[scenario('separate'),input('down',.25),input('drop',.64)],[scenario('one-row'),input('down',.22),input('drop',.6)]],
 '21':[[blank(),type('tail',.04)],[run(),step(.3),step(.66)],[scroll('while (tail->next)'),step(.5)],[step(.08),run(.25),step(.43),step(.61),step(.77),step(.92)]],
 '23':[[blank(),type('clear',.09)],[run(),full(.12),scenario('one-row',.24),input('drop',.42),scenario('two-rows',.6),input('drop',.78)],[scenario('separate'),input('down',.28),input('drop',.66)],[full(),note('// input: board; output: surviving rows + cleared count',.05),full(.46),scenario('one-row',.58),input('drop',.82)]],
 '25':[[source('buggy'),run(.08),scenario('right-wall',.18),input('right',.46),note('// expected: right-wall input must preserve x',.72)],[scenario('right-wall'),debug(.1),input('right',.2),step(.37),step(.55),step(.75)],[scenario('right-wall'),input('right',.13),step(.38),step(.65)],[step(.03),scenario('left-wall',.16),input('left',.27),step(.46),step(.67),step(.87)]],
 '26':[[blank(),type('movement',.05),run(.8)],[full(),scenario('right-wall',.06),input('right',.25),scenario('empty',.44),input('right',.63),input('left',.81)],[full(),note('// bug: current position changed before collision check',.1)],[full(),scenario('left-wall',.08),input('left',.26),input('right',.46),scenario('right-wall',.64),input('right',.8)]],
 '28':[[source('clear'),note('// expected: 2 rows removed; preserve other rows',.3)],[blank(),type('clear',.04),run(.68),full(.8),scenario('two-rows',.89)],[input('drop',.08),scenario('separate',.34),input('drop',.72)],[full(),note('// choose surviving rows before rebuilding the board',.03),full(.42),scenario('two-rows',.57),input('drop',.79)]],
 '30':[[source('tests'),scroll('check(',.35)],[run(),source('movement',.24),run(.31),full(.42),scenario('right-wall',.5),input('right',.64),scenario('two-rows',.75),input('drop',.87)],[scenario('empty'),input('right',.24),input('down',.57)],[input('rotate',.05),input('right',.25),input('down',.46),input('rotate',.65),input('drop',.82)]],
 '32':[[blank(),type('breakout',.04),run(.5),full(.6),input('left',.72),input('right',.86)],[scenario('paddle-center'),input('left',.55),input('right',.77)],[scenario('paddle-edge'),input('right',.65),input('left',.85)],[scenario('paddle-center'),scenario('paddle-edge',.5)]],
 '34':[[blank(.1)],[type('node',.07),run(.76)],[step(.2),step(.62)],[source('pair'),run(.05),step(.28),step(.46),step(.63),step(.79),step(.92)]]
};
const old=fs.existsSync(reportFile)?read(reportFile):{takes:[]};if(old.status==='recording')try{process.kill(old.pid,0);throw Error('Another final capture is active');}catch(e){if(e.code!=='ESRCH')throw e;}
const report={...old,pid:process.pid,status:'recording',inputs,method:'Actions scheduled from current reviewed narration paragraph starts; wall-clock actual execution, no looping, slow motion, or artificial frame padding.'};
const save=()=>{report.updatedAt=new Date().toISOString();fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n');};
async function record(s){
 const prior=report.takes.find(t=>t.id===s.id&&t.status==='finished'&&!t.supersededReason);if(prior){assert.equal(prior.voiceSha256,s.audioSha256);assert.deepEqual(prior.inputs,inputs);assert.equal(hash(path.join(root,prior.finalVideo)),prior.finalSha256);Object.assign(s,{actualVideo:prior.finalVideo,actualMediaVerified:true});return;}
 const mode=['03','05','07','09','10','21','34'].includes(s.id)?'cpp':s.id==='32'?'breakout':'blocks',paragraphs=plan.paragraphs.filter(p=>p.scene===s.id);assert.equal(paragraphs.length,schedules[s.id].length);
 const actions=paragraphs.flatMap((p,i)=>schedules[s.id][i].map(a=>({...a,paragraph:i+1,target:(i===0?0:p.start-s.start)+a.f*((i===paragraphs.length-1?s.seconds:paragraphs[i+1].start-s.start)-(i===0?0:p.start-s.start))}))).sort((a,b)=>a.target-b.target);
 const attempt=report.takes.filter(t=>t.id===s.id).length+1,suffix=attempt>1?'-attempt'+attempt:'',raw=path.join(src,'scene-'+s.id+suffix+'.mp4'),out=path.join(cuts,'scene-'+s.id+suffix+'.mp4'),framesDir=path.join(src,'frames-'+s.id+suffix);assert(!fs.existsSync(raw)&&!fs.existsSync(out),'Preserve earlier final media');fs.mkdirSync(framesDir,{recursive:true});fs.writeFileSync(path.join(framesDir,'.gitignore'),'*\n');
 const t={id:s.id,status:'recording',inputs,voiceSha256:s.audioSha256,actions:[],errors:[],rawVideo:rel(raw),finalVideo:rel(out)};report.takes.push(t);save();
 const browser=await puppeteer.launch({headless:true,args:['--disable-gpu','--disable-accelerated-2d-canvas'],protocolTimeout:120000});
 try{const p=await browser.newPage();await p.setViewport({width:1920,height:1080});p.on('pageerror',e=>t.errors.push(String(e)));await p.goto('http://127.0.0.1:9341');await p.waitForFunction(()=>window.workbench);if(mode!=='cpp')await p.click(`[data-mode="${mode}"]`);await p.evaluate(()=>document.fonts.ready);
 const cdp=await p.createCDPSession(),frames=[];let began=0;cdp.on('Page.screencastFrame',e=>{if(!began)began=Date.now();const file=String(frames.length).padStart(6,'0')+'.jpg';fs.writeFileSync(path.join(framesDir,file),Buffer.from(e.data,'base64'));frames.push({file,timestamp:e.metadata.timestamp});cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId}).catch(()=>{});});await cdp.send('Page.startScreencast',{format:'jpeg',quality:94,maxWidth:1920,maxHeight:1080,everyNthFrame:1});while(!began)await wait(10);
 for(const [i,a]of actions.entries()){
  await wait(a.target*1000-(Date.now()-began));const actual=(Date.now()-began)/1000;
  if(a.kind==='source')await p.select('#lesson',a.arg);
  else if(a.kind==='type'){const code=(mode==='cpp'?catalog.cpp:catalog.js)[a.arg],available=Math.max(.5,(actions[i+1]?.target??s.seconds)-actual-.2);await p.click('#editor');await p.keyboard.down('Control');await p.keyboard.press('A');await p.keyboard.up('Control');await p.type('#editor',code,{delay:Math.max(0,Math.min(12,Math.floor(available*800/code.length)))});await p.$eval('#editor',e=>e.scrollTop=0);}
  else if(a.kind==='scroll')await p.$eval('#editor',(e,text)=>{const pos=e.value.indexOf(text);if(pos>=0){e.focus();e.setSelectionRange(pos,pos+text.length);e.scrollTop=Math.max(0,(e.value.slice(0,pos).split('\n').length-5)*38);}},a.arg);
  else if(a.kind==='note'){await p.click('#editor');await p.keyboard.down('Control');await p.keyboard.press('Home');await p.keyboard.up('Control');await p.keyboard.type(a.arg+'\n',{delay:8});}
  else if(a.kind==='full')await p.click(await p.evaluate(()=>document.body.classList.contains('full'))?'#return-editor':'#view-toggle');
  else if(a.kind==='scenario')await p.click(`[data-scenario="${a.arg}"]`);
  else if(a.kind==='input')await p.click(`[data-input="${a.arg}"]`);
  else {await p.click('#'+a.kind);if(a.kind==='run'&&mode==='cpp')await p.waitForFunction(()=>/중단:|종료 코드|빌드 실패/.test(document.querySelector('#status').textContent),{timeout:30000});}
  t.actions.push({...a,actual,finished:(Date.now()-began)/1000,status:await p.$eval('#status',e=>e.textContent),game:mode==='cpp'?undefined:await p.evaluate(()=>workbench.getGame())});save();
 }
 assert((Date.now()-began)/1000<s.seconds+.4,'Actions exceeded narration scene; revise schedule');await wait((s.seconds+.25)*1000-(Date.now()-began));
 // Ask the still-running browser for a final real frame, so the source spans
 // the complete narration without using FFmpeg's synthetic tail padding.
 await p.evaluate(()=>document.querySelector('#status').style.outline='1px solid transparent');await p.screenshot({path:path.join(work,'last-'+s.id+'.png')});await wait(100);await cdp.send('Page.stopScreencast');
 t.audit=await p.evaluate(()=>window.audit);assert.deepEqual(t.errors,[]);assert(!t.audit.some(e=>e.type==='build'&&e.exitCode!==0));
 const valid=[...new Map(frames.filter(f=>Number.isFinite(f.timestamp)).map(f=>[f.timestamp,f])).values()].sort((a,b)=>a.timestamp-b.timestamp);fs.writeFileSync(path.join(framesDir,'timestamps.json'),JSON.stringify(valid));
 // CDP may stop sending identical frames. The explicit final screenshot is an
 // actual observation at this wall-clock instant, not a fabricated freeze.
 const last=valid.at(-1);const wallEnd=(Date.now()-began)/1000;if(last.timestamp-valid[0].timestamp<s.seconds){const file='last-observed.jpg';await p.screenshot({path:path.join(framesDir,file),type:'jpeg',quality:94});valid.push({file,timestamp:valid[0].timestamp+wallEnd});}
 t.encoding=require('./encode-capture.cjs')(valid,framesDir,raw);const rawSeconds=+JSON.parse(spawnSync('ffprobe',['-v','error','-show_entries','format=duration','-of','json',raw],{encoding:'utf8',windowsHide:true}).stdout).format.duration;assert(rawSeconds>=s.seconds);
 const enc=spawnSync('ffmpeg',['-v','error','-y','-threads','2','-i',raw,'-vf','fps=60','-frames:v',String(s.frames),'-an','-c:v','libx264','-threads','3','-preset','veryfast','-crf','19','-pix_fmt','yuv420p','-video_track_timescale','90000','-movflags','+faststart',out],{encoding:'utf8',windowsHide:true});assert.equal(enc.status,0,enc.stderr);
 const probe=JSON.parse(spawnSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',out],{encoding:'utf8',windowsHide:true}).stdout);assert.equal(+probe.streams[0].nb_frames,s.frames);
 Object.assign(t,{status:'finished',rawSeconds,seconds:s.seconds,frames:s.frames,rawSha256:hash(raw),finalSha256:hash(out),maxActionLateness:Math.max(...t.actions.map(a=>a.actual-a.target)),finishedAt:new Date().toISOString(),visualReview:'pending'});Object.assign(s,{actualVideo:rel(out),actualMediaVerified:true,actualCapture:rel(reportFile)});save();fs.writeFileSync(planPath,JSON.stringify(plan,null,2)+'\n');console.log('Voice-timed actual scene '+s.id+': '+s.seconds.toFixed(2)+'s');
 }catch(e){t.status='failed';t.error=String(e);save();throw e;}finally{await browser.close();}
}
(async()=>{save();const selected=process.argv.slice(2);for(const s of plan.scenes.filter(s=>s.classification!=='explanation'&&(!selected.length||selected.includes(s.id))))await record(s);plan.cuts=plan.scenes.filter(s=>s.classification!=='explanation'&&s.actualMediaVerified).map(s=>({id:s.id,key:'owned-'+s.id,source:s.actualVideo,sourceIn:0,sourceOut:s.seconds,timelineStart:s.start,timelineEnd:s.start+s.seconds,classification:'actual-development-action',claim:read(path.join(root,'projects/blank-project-coding/planning/storyboard.json')).scenes.find(b=>b.id===s.id).claim}));fs.writeFileSync(planPath,JSON.stringify(plan,null,2)+'\n');report.status='finished-awaiting-visual-review';save();})().catch(e=>{console.error(e);process.exitCode=1;});
