const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'../../..'),dest=path.join(root,'motion-canvas/src/projects/blank-project-coding'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
fs.mkdirSync(path.join(dest,'scenes'),{recursive:true});fs.mkdirSync(path.join(dest,'assets'),{recursive:true});
const storyboard=read('projects/blank-project-coding/planning/storyboard.json');
const plan={fps:60,introSeconds:2,outroSeconds:10,scenes:storyboard.scenes.map(s=>({id:s.id,classification:s.classification==='explanation'?'explanation':'actual',seconds:s.plannedSeconds,frames:s.plannedFrames,actualVideo:`shared/assets/blank-project-coding/final-cuts/scene-${s.id}.mp4`})),timingStatus:'planning-only-pending-measured-voice'};
const pp=path.join(dest,'production-plan.json');if(!fs.existsSync(pp))fs.writeFileSync(pp,JSON.stringify(plan,null,2)+'\n');
const actual=storyboard.scenes.filter(s=>s.classification!=='explanation').map(s=>s.id);
for(const s of storyboard.scenes){fs.writeFileSync(path.join(dest,'scenes',`scene${s.id}.tsx`),`import {makeScene2D} from '@motion-canvas/2d';\nimport {${actual.includes(s.id)?'actualScene':'explainScene'}} from './${actual.includes(s.id)?'actual-scene':'concepts'}';\nexport default makeScene2D(function*(view){yield* ${actual.includes(s.id)?'actualScene':'explainScene'}(view,'${s.id}');});\n`);}
const imports=storyboard.scenes.map(s=>`import s${s.id} from './scenes/scene${s.id}?scene';`).join('\n'),prefix="import {makeProject} from '@motion-canvas/core';\nimport intro from '../small-window-game-design/intro-cats-v2/scene?scene';\nimport outro from './scenes/membership-outro?scene';\n";
fs.writeFileSync(path.join(dest,'project.ts'),prefix+imports+"\nimport audio from './assets/final-mix.wav';\nexport default makeProject({name:'blank-project-coding',scenes:[intro,"+storyboard.scenes.map(s=>'s'+s.id).join(',')+",outro],audio});\n");
fs.writeFileSync(path.join(dest,'explanation-project.ts'),prefix+storyboard.scenes.filter(s=>!actual.includes(s.id)).map(s=>`import s${s.id} from './scenes/scene${s.id}?scene';`).join('\n')+"\nexport default makeProject({name:'blank-project-coding-explanation-reel',scenes:[intro,"+storyboard.scenes.filter(s=>!actual.includes(s.id)).map(s=>'s'+s.id).join(',')+",outro]});\n");
const wav=path.join(dest,'assets/final-mix.wav');if(!fs.existsSync(wav)){const b=Buffer.alloc(48044);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(24000,24);b.writeUInt32LE(48000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(48000,40);fs.writeFileSync(wav,b);}
const registry=read('motion-canvas/projects.json');for(const suffix of ['project.ts','explanation-project.ts']){const entry='./src/projects/blank-project-coding/'+suffix;if(!registry.includes(entry))registry.push(entry);}fs.writeFileSync(path.join(root,'motion-canvas/projects.json'),JSON.stringify(registry,null,2)+'\n');
const m=read('projects/blank-project-coding/project.json');m.engines=['motion-canvas'];m.paths.editorAudioMix='motion-canvas/src/projects/blank-project-coding/assets/final-mix.wav';m.paths.scriptEn='projects/blank-project-coding/script/narration.en.json';m.production.engineProjectsCreated=true;fs.writeFileSync(path.join(root,'projects/blank-project-coding/project.json'),JSON.stringify(m,null,2)+'\n');console.log('34 independent scene modules and full/reel projects created; timing remains provisional.');
