const fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'../../..'),manifestPath=path.join(__dirname,'../project.json'),m=JSON.parse(fs.readFileSync(manifestPath,'utf8')),script=JSON.parse(fs.readFileSync(path.join(root,m.paths.script),'utf8')),board=JSON.parse(fs.readFileSync(path.join(__dirname,'../planning/storyboard.json'),'utf8'));
const partial=structuredClone(m);partial.paths.script='projects/blank-project-coding/script/explanation-partial.ko.json';partial.tts.filenameStem+='-explanation-partial';
fs.writeFileSync(path.join(root,partial.paths.script),JSON.stringify({...script,title:script.title+' (설명 음성 부분 생성)',scenes:script.scenes.filter(s=>board.scenes.find(b=>b.id===s.id).classification==='explanation')},null,2)+'\n');fs.writeFileSync(path.join(__dirname,'explanation-partial.manifest.json'),JSON.stringify(partial,null,2)+'\n');
const device=process.argv.includes('--gpu')?'cuda:0':'cpu';
const old=path.join(__dirname,'voice-process.json');if(fs.existsSync(old))fs.copyFileSync(old,path.join(__dirname,'voice-process-'+Date.now()+'.json'));
const state={pid:process.pid,startedAt:new Date().toISOString(),device,reason:device==='cpu'?'GPU memory is occupied by existing user processes; preserve them and use the same approved model/reference on CPU.':'GPU memory became available; preserve completed scene chunks and resume the same approved model/reference on GPU.',status:'running',stages:[]};
const save=()=>fs.writeFileSync(path.join(__dirname,'voice-process.json'),JSON.stringify(state,null,2)+'\n');save();
function run(stage,args){return new Promise((resolve,reject)=>{const log=fs.openSync(path.join(__dirname,stage+'.log'),'a');const p=spawn(path.join(root,'qwen3-tts/.venv/Scripts/python.exe'),['-X','utf8',...args],{cwd:root,windowsHide:true,stdio:['ignore',log,log]});const row={stage,pid:p.pid,startedAt:new Date().toISOString(),status:'running',args};state.stages.push(row);save();p.on('exit',code=>{fs.closeSync(log);Object.assign(row,{status:code===0?'finished':'failed',exitCode:code,finishedAt:new Date().toISOString()});save();if(code)reject(Error(stage+' exit '+code));else resolve();});p.on('error',reject);});}
(async()=>{await run('voice-explanations',['qwen3-tts/render_narration.py','--project',m.slug,'--manifest','projects/blank-project-coding/production/explanation-partial.manifest.json','--device',device,'--batch-size','1']);state.status='waiting-for-actual-source-review';save();const gate=path.join(__dirname,'actual-source-review.json');while(!fs.existsSync(gate)||!JSON.parse(fs.readFileSync(gate,'utf8')).ttsSourcePlanReady)await new Promise(r=>setTimeout(r,15000));state.status='running';save();await run('voice-full',['qwen3-tts/render_narration.py','--project',m.slug,'--device',device,'--batch-size','1']);await run('asr-full',['qwen3-tts/review_project_narration.py','--project',m.slug,'--device',device==='cpu'?'cpu':'cuda']);state.status='finished-technical-review-needed';save();})().catch(e=>{state.status='failed';state.error=String(e);save();console.error(e);process.exitCode=1;});
