"""Record the actual completed production and schedule commits, without predicting this file's future commit."""
import json
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[3]
BASE='projects/character-parameters'; PUB=BASE+'/publishing'; BATCH='production/batches/sakurai-planning-game-design'
def read(p):return json.loads((ROOT/p).read_text(encoding='utf-8-sig'))
def write(p,v):(ROOT/p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
now=datetime.now(timezone.utc).isoformat()
production=read(PUB+'/private-delivery-git-verification-v1.json'); evidence=read(PUB+'/schedule-evidence-git-verification-v1.json')
assert all(x['pushed'] and x['exactLocalRemoteMatch'] and x['allRemoteBlobsVerified'] and x['externalIndexUnchanged'] for x in [production,evidence])
schedule=read(PUB+'/schedule-direct-review-v1.json'); receipt=read(PUB+'/youtube-upload-v1.json')
assert receipt['scheduled'] and receipt['fullSettingsVerified'] and schedule['savedReopened']
receipt.update(status='completed-reviewed-scheduled-and-git-delivered',publishingGitDelivered=True,publishingGitCommit=evidence['commit'],publishingGitVerification=PUB+'/schedule-evidence-git-verification-v1.json',updatedAt=now)
write(PUB+'/youtube-upload-v1.json',receipt)
project=read(BASE+'/project.json');project['status']='completed-reviewed-scheduled-and-git-delivered';project['publishing'].update(publishingGitDelivered=True,publishingGitCommit=evidence['commit']);write(BASE+'/project.json',project)
next_action='limited-color-world: read full original research, existing concept/chapter/KOEN content and actual current Studio before a distinct check; no new script/TTS/MC until approved source actions.'
checkpoint=read(BASE+'/production/latest-checkpoint.json');checkpoint.update(stage='completed-reviewed-scheduled-and-git-delivered',publishingGitDelivered=True,publishingGitCommit=evidence['commit'],recordedAt=now,nextSlug='limited-color-world',nextAction=next_action);write(BASE+'/production/latest-checkpoint.json',checkpoint)
queue=read(BATCH+'/queue.json');item=next(x for x in queue['items'] if x['slug']=='character-parameters');item.update(status='complete',stage='reviewed-delivered-git-verified-and-scheduled',publishingGitDelivered=True,publishingGitCommit=evidence['commit'],publishingGitVerification=PUB+'/schedule-evidence-git-verification-v1.json',nextAction=next_action,updatedAt=now);item['checkpoints'].update(publishingGit=True,scheduled=True);queue.update(nextSlug='limited-color-world',lastProgressAt=now,updatedAt=now);write(BATCH+'/queue.json',queue)
readme=ROOT/BASE/'README.md';text=readme.read_text(encoding='utf-8-sig');text=text.replace('예약/evidence 선택Git은 이어서 전달한다.','예약 증거19개 명시blob도 실제 `'+evidence['commit']+'`로 일반push한 뒤 local/remote와 모든blob·외부index 보존을 확인했다. 최종 handoff는 이미 존재하는 이 두 commit만 기록하며 미래 자기SHA를 추정하지 않는다.');readme.write_text(text,encoding='utf-8',newline='\n')
prefix='2026-10-10 latest completed delivery: character-parameters nic5Sp6dylQ is reviewed, four-file collected, fully configured and actually scheduled Oct30 09:00 Asia/Seoul. Production '+production['commit']+' verified482blobs and scheduling evidence '+evidence['commit']+' verified19blobs through normal origin/main pushes and unchanged external index bytes/entries. Five individually reviewed essential rasters total (thumbnail plus four minimal publishing proofs); all QA/source/media remain local. Historical schedule ledger25entries/design11lecture14 includes already-published picking-sides; current future list24rows preserves its prior23dates. Seventeen reviewed Sakurai deliveries, natural-tutorials duplicate excluded1, remaining6queued; next limited-color-world requires its own full source/content/current Studio duplicate review. Actual picking public coaching comment UgynTM-MA24mW_yhUx14AaABAg is posted/pinned/reopened. Character whole human listening/pronunciation/final public rights/Nimbus/handles/backup/dubbing/optionalCC and its future publication comment remain pending. Completed media/TTS/ASR/QA/collection/upload/Git/schedule are not repeated. The paragraphs below are historical; current individual receipts take precedence.\n\n'
write(PUB+'/schedule-batch-readme-prefix-v1.json',{'prefix':prefix,'recordedAt':now})
batch_readme=ROOT/BATCH/'README.md';old=batch_readme.read_text(encoding='utf-8-sig');batch_readme.write_text(prefix+old,encoding='utf-8',newline='\n')
handoff=dict(schemaVersion=1,slug='character-parameters',actualVideoId='nic5Sp6dylQ',status='completed-reviewed-scheduled-and-git-delivered',recordedAt=now,productionCommit=production['commit'],productionVerifiedBlobs=production['verifiedBlobCount'],publishingEvidenceCommit=evidence['commit'],publishingVerifiedBlobs=evidence['verifiedBlobCount'],productionVerification=PUB+'/private-delivery-git-verification-v1.json',publishingVerification=PUB+'/schedule-evidence-git-verification-v1.json',finalOwnCommit='Record only after actual commit exists; no predicted SHA.',schedule=schedule,receipt=PUB+'/youtube-upload-v1.json',finalFrames=23397,durationSeconds=389.95,format='1920x1080p60;90000timebase;PTS1500;both whole decodes0;identicalAAC',bodyFrames=22677,actualFrames=13606,explanationFrames=9071,ratioRoundingErrorFrames=-0.2,catFrames=120,originalMembershipFrames=600,encodedSamplesDirectlyReviewed=1266,boardsDirectlyReviewed=211,koCues=201,enCues=95,cuts=41,paragraphs=37,pcmPlacements=17,blackSpatialSections=17,currentMixedWholeAsr=12,currentMixedIndependentContexts=37,loudnessLufs=-16.05,truePeakDbtp=-2.01,finalPixelReview=BASE+'/production/final-v1/final-pixel-direct-review-v1.json',collectionReview=BASE+'/production/collection-private-preflight-v1.json',privateSettingsReview=PUB+'/private-settings-direct-review-v1.json',essentialRasterTotal=5,mediaAndQaRastersAdded=0,externalIndexBytesAndEntriesPreserved=True,researchManipulationInCpuPublishingGitScheduling=0,newResearchResumeClaim=False,humanWholeListeningApproved=False,humanPronunciationApproved=False,publicRightsApproved=False,pendingHumanAndPublicationFollowups=receipt['pending'],nextSlug='limited-color-world',remainingQueued=6,nextAction=next_action)
write(PUB+'/final-handoff-v1.json',handoff)
print(json.dumps({'sealedActualCommits':[production['commit'],evidence['commit']],'scheduled':True,'remaining':6,'next':'limited-color-world'}))
