// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 211.53333333333333;

export const SCENE_STARTS = [
  0.0,
  38.0,
  69.53333333333333,
  104.73333333333333,
  139.76666666666668,
  174.16666666666666,
] as const;

export const SCENE_DURATIONS = [
  38.0,
  31.533333333333335,
  35.2,
  35.03333333333333,
  34.4,
  37.36666666666667,
] as const;

export const SCENE_TITLES = [
  "점수와 성공 인정은 구분된다",
  "성공과 가까운 순간에 반응하기",
  "실제로 해낸 행동을 말하기",
  "성과에 맞는 칭찬의 강도",
  "실패를 숨기지 않는 긍정",
  "다음 행동의 자리를 남기기",
] as const;

export const TOTAL_FRAMES = 12692;
