// GENERATED by production/build_episode_audio.py; measured at 60fps
export const NARRATION_FPS=60;
export const TOTAL_DURATION=409.95;
export const TOTAL_FRAMES=24597;
export const SCENE_STARTS=[0.0, 39.38333333333333, 83.48333333333333, 131.5, 180.88333333333333, 228.26666666666668, 280.45, 319.5833333333333, 362.56666666666666] as const;
export const SCENE_DURATIONS=[39.38333333333333, 44.1, 48.016666666666666, 49.38333333333333, 47.38333333333333, 52.18333333333333, 39.13333333333333, 42.983333333333334, 47.38333333333333] as const;
export const SCENE_TITLES=["게임을 만드는 사람들", "한 장면을 만드는 네 가지 시선", "게임 기획자 — 플레이 경험을 설계하는 사람", "게임 프로그래머 — 규칙을 작동하게 만드는 사람", "2D 아티스트 — 게임의 모습을 먼저 보여주는 사람", "3D 아티스트 — 입체 세계를 게임 안에 세우는 사람", "같은 직군 안에서도 역할은 나뉜다", "게임은 역할 사이의 반복으로 완성된다", "내 역할을 찾는 가장 작은 시작"] as const;
