// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 212.56666666666666;

export const SCENE_STARTS = [
  0.0,
  30.4,
  64.16666666666667,
  96.86666666666666,
  138.4,
  179.03333333333333,
] as const;

export const SCENE_DURATIONS = [
  30.4,
  33.766666666666666,
  32.7,
  41.53333333333333,
  40.63333333333333,
  33.53333333333333,
] as const;

export const SCENE_TITLES = [
  "같이 만들어도 느낌이 다른 이유",
  "먼저 한 번의 행동을 잘라 보자",
  "좋아 보이는 이유를 조건으로 적자",
  "하나를 빼면 무엇이 달라질까",
  "남길 판단을 골라 새 규칙으로 묶자",
  "기능 목록보다 플레이 기록을 남기자",
] as const;

export const TOTAL_FRAMES = 12754;
