"""Record direct local pixels and correct the proposed source/audio mapping.
No PCM, final mix, captions or video are generated by this planning step.
"""
from pathlib import Path
from datetime import datetime, timezone
import copy, json, hashlib

ROOT=Path(__file__).resolve().parents[3]
BASE=Path(__file__).resolve().parent
PROJECT=BASE.parent
PROOF=ROOT/'production/batches/sakurai-planning-game-design/proof-avoid-game-comparisons'
def read(p): return json.loads(p.read_text(encoding='utf-8-sig'))
def save(p,d): p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return p.relative_to(ROOT).as_posix()
now=datetime.now(timezone.utc).isoformat()
destination=BASE/'native-cue-proposal-v2.json'
assert not destination.exists(), 'Read the saved correction; do not repeat planning.'
state=read(BASE/'native-cue-edges-execution.json')
assert state['exitCode']==0 and state['cpuJobs']==0
review={
 'schemaVersion':1,'reviewedAt':now,'status':'direct-pixels-reviewed-proposal-corrected-final-cues-pending',
 'executionState':rel(BASE/'native-cue-edges-execution.json'),
 'executionStateSha256':sha(BASE/'native-cue-edges-execution.json'),
 'sheetsRead':[x for s in state['sources'] for x in s['sheets']],
 'nativeSamplesRead':sum(len(s['frames']) for s in state['sources']),
 'extraExistingSheetsRead':[
  'research-local/native-review-v1/WFIvd2HrMNY/boundary-sheet-01.jpg',
  *['research-local/native-review-plucky-mine/CJ0_Xh59b98/action-sheet-'+str(n).zfill(2)+'.jpg' for n in [3,4,5,8,9,10,12,13,14]],
  'research-local/native-review-v1/JdNZo7E_hXU/action-sheet-04.jpg',
  'research-local/game-discovery/JdNZo7E_hXU/sheet-04.jpg',
  'research-local/game-discovery/JdNZo7E_hXU/sheet-05.jpg'],
 'observations':[
  {'source':'WFIvd2HrMNY','finding':'Native826 shows the music-page walk;827/828 show the gap.960 is the gap jump;961/962 show stairs. Rounded14/16.5-second edit assumptions were wrong.','rejectedProposedEnds':[839,989],'correctExclusiveEnds':[827,961]},
  {'source':'CJ0_Xh59b98','finding':'266–269 already show a strike/hit, not an entirely pre-strike walk.794–797 approach a horned foe;2411–2414 traverse the virtual book;3709–3712 show dark-page combat;9345–9348 show combat before the red chest.','claimLimit':'No button, universal rule, automatic victory or closed-blue-chest opening inferred.'},
  {'source':'CJ0_Xh59b98','finding':'6173–6176 show doubled book outlines during the same portal approach. Existing100–108.9 and147–153 sequences both continue from3D virtual character/green opening to2D avatar and combat;105.5 and152.5 samples are clear2D.','claimLimit':'Record observable entry/appearance and preserve continuity; do not identify a rendering technique or turn an unrelated editorial dissolve into gameplay. Final continuous-cut review remains pending.'},
  {'source':'h27ZF-hKKYM','finding':'4540–4543 are spool/card ledges;4858–4861 are the enemy hit;5268–5271 are already at the blue-wall opening.7978–7981 and8623–8626 show airborne printed-cylinder attacks;9688–9691 show low virtual-desk melee.','claimLimit':'Use separate excerpts for the spool/hit/wall sentence; no continuous-input or fuel-rule claim. Low avatar/UI require final framing.'},
  {'source':'xREgLxEzZE4','finding':'86.4–86.7 transition from physical advertising;86.8–87.8 purple-wall rocket;87.9–88.9 giant-hand throw;89–89.8 yellow-page vertical movement;89.9–90.9 virtual-book emergence;91–92 axe/trunk;92.1 onward title.','decision':'Continue to hold the short montage. Axe/trunk is not enemy combat; no new unique actual seconds approved from this trailer.'},
  {'source':'CJ0_Xh59b98','finding':'42.5–44 samples lead to camera pullback/standing;90.5–93 mainly camera/book setup before key travel.29.997–31.5 are pre-opening/NPC context.','decision':'Do not expand these gaps merely to fill the ratio.'},
  {'source':'JdNZo7E_hXU','finding':'62–65 discovery shows bright-page fighting before66–69 menus. Menus show Invincibility and One Hit Kill enabled;70–72 show virtual-desk combat.','decision':'Inspect new native action/cut edges before candidate adoption; carry the option context into any desk-combat use. Menus are explanation, not actual-action quota.'}
 ],
 'original15PcmPreserved':True,'newGitImages':0,'sourceAudioUsed':False,
 'fixedCaptionPixelsApproved':False,'finalFramesApproved':False,'bodyRatioApproved':False,
 'humanContinuousSourcePlayback':'pending','humanWholeListening':'pending'
}
save(BASE/'native-cue-boundary-direct-review.json',review)
for source in state['sources']:
 source.update(directReview=True,status='direct-pixels-reviewed-final-cut-captions-pending')
state.update(status='closed-native-edge-pixels-reviewed-proposal-corrections-required',directReview=rel(BASE/'native-cue-boundary-direct-review.json'),directPixelReview=True,exactBoundaryApproval=False,bodyRatioApproved=False,updatedAt=now)
save(BASE/'native-cue-edges-execution.json',state)
proposal=copy.deepcopy(read(BASE/'native-cue-proposal.json'))
proposal.update(schemaVersion=2,createdAt=now,status='corrected-native-source-and-current15-audio-proposal-awaiting-final-cues',supersedes=rel(BASE/'native-cue-proposal.json'),directPixelReview=rel(BASE/'native-cue-boundary-direct-review.json'))
measured=read(BASE/'measured-paragraphs-expanded15.json')
measurements={s['id']:s for s in measured['scenes']}
def duration(c):
 fps=c['nativeFps'];c.update(inSeconds=c['startFrame']/fps,outSeconds=c['endFrameExclusive']/fps,seconds=(c['endFrameExclusive']-c['startFrame'])/fps)
def group(scene,p): return next(g for g in proposal['groups'] if g['sceneId']==scene and g['paragraph']==p)
excluded={'action-08','action-55','action-14','action-23','action-17','action-12','action-13'}
removed=[]
for g in proposal['groups']:
 removed.extend(c for c in g['sourceCuts'] if c['id'] in excluded)
 g['sourceCuts']=[c for c in g['sourceCuts'] if c['id'] not in excluded]
 for c in g['sourceCuts']:
  if c['id']=='action-35':c['endFrameExclusive']=827;c['newExactBoundaryPixelReview']=True
  if c['id']=='action-36':c['startFrame']=827;c['endFrameExclusive']=961;c['newExactBoundaryPixelReview']=True
  duration(c)
 # All measured current15 paragraphs are locked;14 uses the continuous special prefix.
 if g['sceneId']=='15':
  p=next(p for p in measurements['15']['paragraphs'] if p['paragraph']==g['paragraph'])
  g.update(audioFromSeconds=p['pcmFromSample']/24000,audioToSeconds=p['pcmToSample']/24000,voiceSeconds=p['pcmSeconds'])
# Mine combat must not appear beneath the Pepper device claim.
pepper=group('12',2);mine=group('12',3)
moved=[c for c in pepper['sourceCuts'] if c['sourceVideoId']=='CJ0_Xh59b98']
pepper['sourceCuts']=[c for c in pepper['sourceCuts'] if c not in moved]
for c in moved:c.update(sceneId='12',paragraph=3)
mine['sourceCuts'].extend(moved)
pepper.update(whiteExplanationTail=True,note='Pepper cannon/mech only. The unknown cost/win-condition tail is a white2.5D question. Mine combat moved to the following generic condition paragraph.')
group('15',3).update(whiteExplanationTail=True,note='Keep water/lava emergence and a visible boss shot; reject0.3/0.5-second flashes. Movement/target wording is a white comparison after the actual shots. Obtain a longer firing action if the observed shot is insufficient.')
group('04',1)['note']='Music-page walk stops before native827 gap cut. Gap starts827 and stops before native961 stair cut; earlier rounded14/16.5-second extension was rejected.'
for g in proposal['groups']:
 g['sourceSeconds']=sum(c['seconds'] for c in g['sourceCuts'])
 voice=g['voiceSeconds']
 g['minimumActionObservationExtraSeconds']=max(0,g['sourceSeconds']-voice)
 g['unresolvedVoiceCoverageSeconds']=0 if g['whiteExplanationTail'] else max(0,voice-g['sourceSeconds'])
 g['proposedExplanationSeconds']=max(0,voice-g['sourceSeconds']) if g['whiteExplanationTail'] else 0
cuts=[c for g in proposal['groups'] for c in g['sourceCuts']]
for sid in {c['sourceVideoId'] for c in cuts}:
 ordered=sorted([c for c in cuts if c['sourceVideoId']==sid],key=lambda c:c['startFrame'])
 for a,b in zip(ordered,ordered[1:]):assert a['endFrameExclusive']<=b['startFrame'],(sid,a['id'],b['id'])
originalWhite=sum(s['speechSeconds'] for s in measured['scenes'] if s['id'] in ['01','03','05','07','09','11'])
additionalWhite=sum(g['proposedExplanationSeconds'] for g in proposal['groups'])
additionalWhite+=measurements['13']['paragraphs'][-1]['pcmSeconds']
additionalWhite+=measurements['14']['speechSeconds']-group('14',1)['audioToSeconds']
actual=sum(c['seconds'] for c in cuts)
proposal.update(sourceUniqueSeconds=actual,sourceAllNonOverlapping=True,excludedMicroCuts=[{'id':c['id'],'sourceVideoId':c['sourceVideoId'],'seconds':c['seconds'],'reason':'Subsecond isolated flash is too brief for the claimed action; not used to fill actual quota.'} for c in removed],allCurrent15PcmPreserved=True,current15Index=rel(BASE/'narration-expanded15-index.json'),currentSpeechSeconds=sum(s['speechSeconds'] for s in measured['scenes']),proposedExplanationSeconds=originalWhite+additionalWhite,minimumRelatedAdditionalActualSeconds=max(0,1.5*(originalWhite+additionalWhite)-actual),bodyRatioApproved=False,exactNewNativeEdgesReviewed=False,allCaptionPixelsReviewed=False)
save(destination,proposal)
qpath=PROOF.parent/'queue.json';q=read(qpath);task=next(i for i in q['items'] if i['slug']=='avoid-game-comparisons')
task.update(stage='current15-corrected-native-cue-plan-additional-context-actions-review',updatedAt=now,nextAction='Inspect new native accessibility-source combat before candidate adoption; preserve all15 PCM and six white explanations. Complete sentence/cut context, mixed diagrams, fixed-caption framing and exact60:40 before final mix/render/QA/private delivery.')
task['nativeCueEdgeReview'].update(status=state['status'],directPixelReview=True,review=rel(BASE/'native-cue-boundary-direct-review.json'),correctedProposal=rel(destination),bodyRatioApproved=False)
task['execution'].update(observedAt=now,status='closed-all15-ASR-and-new-edge-pixels-reviewed',alive=False,cpuProductionJobs=0,primaryCpuProductionJobs=0,activeTasks=[],nextAction=task['nextAction'])
q.update(updatedAt=now,lastProgressAt=now);save(qpath,q)
for p in [BASE/'latest-checkpoint.json',PROOF/'latest-checkpoint.json']:
 d=read(p)
 for k in ['stage','updatedAt','nextAction','execution','nativeCueEdgeReview']:d[k]=task[k]
 d['nativeCueProposal']=rel(destination);d['current15TechnicalNarrationApproved']=True;d['bodyRatioApproved']=False;save(p,d)
print(json.dumps({'current15SpeechSeconds':proposal['currentSpeechSeconds'],'candidateActualSeconds':actual,'proposedExplanationSeconds':proposal['proposedExplanationSeconds'],'relatedActualStillNeeded':proposal['minimumRelatedAdditionalActualSeconds'],'microCutsExcluded':len(removed),'finalApproved':False},ensure_ascii=False))
