// GENERATED by scripts/build-ai-cs-continuous-audio.cjs.
// Same full mix as the AAC master; PCM WAV supports VS Code playback.
import audio from './assets/mix-v6-artist-music-review.wav';
export default audio;
