const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../..'),base=path.dirname(__dirname),slug='counting-animation-frames';
const sources=[['megaman11-capcom','Mega Man 11','3aSC5A726f0','Official Capcom Europe','https://www.youtube.com/@capcomuk'],['mhrise-capcom','Monster Hunter Rise','n-5jAq2Nyhs','Monster Hunter','https://www.youtube.com/@monsterhunter']].map(([key,game,id,owner,channel])=>{
 const raw=path.join(root,'shared/assets',slug,'raw',key+'.mp4'),info=JSON.parse(fs.readFileSync(raw.replace('.mp4','.info.json'),'utf8'));
 if(info.id!==id)throw Error('Unexpected source ID');
 return {game,sourceVideoId:id,url:'https://www.youtube.com/watch?v='+id,recordingOwner:owner,channel,metadataOwner:info.uploader,metadataChannelId:info.channel_id,title:info.title,durationSeconds:info.duration,sourceFps:info.fps,width:info.width,height:info.height,localFile:path.relative(root,raw).replaceAll('\\','/'),sha256:crypto.createHash('sha256').update(fs.readFileSync(raw)).digest('hex'),downloadedAt:new Date().toISOString(),visualReview:'3-second-grid contact sheet inspected; only gameplay actions selected. Excluded intro/rating/history/title cards. Final exact cut/cue visual inspection remains pending.',sourceAudio:'video-only acquisition; original soundtrack not used',rights:{policy:'https://www.capcomusa.com/video-policy/Capcom_Video_Policy.pdf',checkedAt:new Date().toISOString(),policyUpdated:'2021-03-15',use:'educational action commentary with original script/test/comparison; short gameplay portions of the rights-holder recording, not raw reposts',commercialUse:'YouTube partner advertising permitted by policy; no paid-exclusive access. Private user review now; public release remains user decision.',licenseStatus:'publisher gameplay policy considered applicable; not a blanket clearance of third-party rights',publicRightsReview:'pending human rights review and actual Studio checks'}};
});
const candidates={schemaVersion:1,reviewedAt:new Date().toISOString(),topic:'Frame count, elapsed time, independent pose/collision clocks and hitpause',priorUseMethod:'Repository rg over project manifests, SOURCES.md and game-candidates.json; completed deconstruct/meaningful sources reviewed. Do not treat absence of a title match as absence of all franchise use.',selected:[{game:'Mega Man 11',why:'Observable jump/preparation/change/ending in a fresh title; avoids assuming exact commercial move counts.',priorUse:{titleFound:false,sourceIdFound:false,newSegment:true}},{game:'Monster Hunter Rise',why:'Fresh official Hunting Horn motion clearly shows preparation, impact and follow-through; exact counts come from our original test.',priorUse:{titleFound:false,sourceIdFound:false,franchisePreviouslyUsed:'Monster Hunter Wilds in visible-rewards; different game and new recording segment',newSegment:true}},{game:'Original Frame Timing Lab',why:'Actual keyboard acceptance, collision/miss, busy-input rejection, fixed 60/30 logic and independent poses/display sampling/hitpause verified in executable captures.',priorUse:{newProjectCode:true,newCapture:true},rights:'Original repository code and original procedural event sound'}],rejected:[{game:'Street Fighter 6',reason:'Excellent timing example but previously used in frame-rate-modern-rendering; prioritize a new title.',priorUse:'F2347gyZp0U at 40–46.5s; reject automatic reuse'},{game:'Street Fighter II',reason:'Already used in frame-rate-modern-rendering; do not recycle source or segment.',priorUse:'myGdMOcdTcE'},{game:'Hades',reason:'Supergiant policy asks for functional public product credit; user omits public description credits. Prefer other suitable sources rather than assuming the requirement waived.',policy:'https://www.supergiantgames.com/blog/policy-on-lets-play-videos/'},{game:'Mega Man 11 / Monster Hunter Rise third-party longplays',reason:'Publisher game policy does not itself establish third-party recording permission. Unconfirmed reuploads/longplays excluded.'},{game:'Super Meat Boy / Hollow Knight / Portal / Skyrim / Subnautica',reason:'Used in the latest two batch videos; fresh titles selected for this topic.'}],sources,prototype:{path:'projects/counting-animation-frames/production/prototype',capturePath:'shared/assets/counting-animation-frames/playtests-v2',normalSpeed:true,loop:false,artificialSlowdown:false,actualInputLogs:['rate','interval','poses','pause','render'].map(mode=>'projects/counting-animation-frames/production/'+mode+'-v2-input-log.json'),humanFunReview:'pending'},warnings:['Human final listening and public rights review remain pending.','Studio copyright/ad checks have not yet run for this new video.','Original Nimbus Audio Library bytes and external backup remain unverified.']};
candidates.prototype.selectedRevisions={rate:'v2',interval:'v3',poses:'v2',pause:'v2',render:'v2'};
candidates.prototype.capturePath='shared/assets/counting-animation-frames/playtests-v2; interval uses playtests-v3';
candidates.prototype.actualInputLogs=Object.entries(candidates.prototype.selectedRevisions).map(([mode,revision])=>'projects/counting-animation-frames/production/'+mode+'-'+revision+'-input-log.json');
candidates.prototype.note='v1 excluded for shared-variable contamination; v2 isolates comparisons and checks all attacks. Interval v3 explicitly labels B as the fixed 12-step default and A as the preparation-only modification.';
candidates.prototype.timeBasis='deterministic fixed-clock simulation and its normal-speed video timeline; not a physical hardware-latency/performance benchmark';
fs.writeFileSync(path.join(base,'sources/game-candidates.json'),JSON.stringify(candidates,null,2)+'\n');
fs.writeFileSync(path.join(base,'sources/source-files.json'),JSON.stringify({sources},null,2)+'\n');
