// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 185.6;

export const SCENE_STARTS = [
  0.0,
  29.666666666666668,
  60.63333333333333,
  92.63333333333334,
  124.0,
  154.0,
] as const;

export const SCENE_DURATIONS = [
  29.666666666666668,
  30.966666666666665,
  32.0,
  31.366666666666667,
  30.0,
  31.6,
] as const;

export const SCENE_TITLES = [
  "느낌을 시간으로 옮기기",
  "프레임 수에는 기준 속도가 필요하다",
  "동작의 어느 구간을 재는가",
  "그림 시계와 판정 시계",
  "멈춤은 어느 시계에 더해지는가",
  "눈으로 찾고 로그로 확인하기",
] as const;

export const TOTAL_FRAMES = 11136;
