"""Prepare reviewed bilingual lecture metadata and preserve existing receipts."""
from pathlib import Path
import json, hashlib, subprocess, sys
ROOT=Path(__file__).resolve().parents[3];slug=sys.argv[1]
assert slug in ['game-math-lines-circles-v2','game-math-bounds-transform-v2']
def read(p):return json.loads(p.read_text(encoding='utf8'))
def write(p,d):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
P=ROOT/'projects'/slug;D=P/'publishing';m=read(P/'project.json');t=read(P/'production/timeline.json');part=m['lecture']['episode']
assert m['finalRender']['currentPixelApproval']
assert not (D/'youtube-upload.json').exists(),'Preserve prepared/uploaded receipt.'
ko=('앞 강의에서 물체의 자세를 구했다면, 이제 두 물체 사이의 연결선을 어떻게 계산할까요? 같은 거리인 점들의 모임인 원에서 시작해 두 점의 차이로 선을 만들고, 비율과 실제 이동 거리의 차이를 작은 숫자로 확인합니다. 마지막에는 기울기로 적기 어려운 세로선을 법선으로 표현해 봅니다. 연결선을 만들었으니 다음 강의에서는 선이 닿을 대상의 크기를 계산합니다. 두 편 중 첫 번째 강의입니다.' if part==1 else '연결선을 만들었지만 선이 닿을 대상의 크기는 아직 모릅니다. 둥근 물체를 구로, 길쭉하고 복잡한 물체를 상자로 감싸는 이유부터 살펴보고, 겹치는 범위를 한 축씩 계산합니다. 이어서 물체가 회전하면 왜 경계를 다시 구해야 하는지 확인하고, 중심과 반크기를 이용해 계산을 이어갑니다. 실제 몸의 접촉과 단순한 경계의 겹침도 구분합니다. 직선과 경계 두 편 중 두 번째 강의입니다.')
en=('After finding an object’s orientation in the previous lecture, how do we calculate a connection between two objects? We start with a circle as a set of equally distant points, form a line from the difference between two points, and use small numbers to separate a dimensionless fraction from travel distance. We then express a vertical line using a normal. Having built the connection, the next lecture will calculate the size of the target it may reach. This is the first of two lectures.' if part==1 else 'We have built a connection, but we still need the size of its target. We explain why round objects can be enclosed by spheres and more complex objects by boxes, then calculate overlapping intervals one axis at a time. Next, we see why rotation requires new bounds and continue the calculation using the center and half-size. We also distinguish actual body contact from overlapping bounds. This is the second lecture on lines and bounds.')
links=[('게임수학 PART2 수업 자료','Game Math PART2 course materials','https://www.yamyamcoding.com/1ea0b1ff-a61e-803f-bd54-cac4f028f6b3'),('얌얌코딩 홈페이지','YamYamCoding website','https://www.yamyamcoding.com/'),('얌얌위키 전체 수업 노트','YamYamWiki course notes','https://www.yamyamcoding.com/0d2adf45-5d1a-43be-a37c-61c94b1ae2c8')]
ko+='\n\n'+'\n\n'.join(a+'\n'+u for a,b,u in links);en+='\n\n'+'\n\n'.join(b+'\n'+u for a,b,u in links)
ids=['LF01','02','LB01','03','04','LC04','LG01','05','06','LP01','LG03','08','LB02','09','LF02'] if part==1 else ['LF03','10','LG04','LP02','11','12','LC13','13','14','LP03','15','LB04','LG05','16','17','LC18','18','LG06','19','LB05','20','LG07','21','22']
titles=['Overview: give the oriented object a connection','Locate the two endpoints in a grapple','Why begin with a circle?','Three descriptions of the same circle','Moving the center introduces linear terms','From a moved circle to a connection','Redirect a beam and observe the result','Separate direction from distance','Lines, segments and rays have different domains','Compare a fraction with distance at the same point','Apply the same fraction to new endpoints','How can we express a vertical line?','Equal distances produce a vertical line','Normals and the perpendicular bisector','The next question: the target’s extent'] if part==1 else ['Overview: the target’s extent and rotated bounds','Visible roundness and collision bounds','Compare a round head with an elongated body','Inside a sphere means close enough to its center','Separate the surface from the interior','Does twice the radius mean twice the size?','Enclosing an elongated body with a round bound','Enclose a complex shape simply','Data for an axis-aligned box','Choose minima and maxima one axis at a time','Build a box from five points','Overlap starts with intervals on one axis','The outline and enclosure of a moved cube','Overlapping bounds do not prove body contact','Candidate checks and precise checks','After overlap, update the rotated values','Rotating only two corners gives wrong bounds','Separate body rotation from screen changes','Camera changes and the reference axes','Why use absolute values for half-size?','Transform the center and half-size','Empty space inside an enclosing range','Decide what the bound encloses','Connect two worked problems']
chapters=[]
for ident,title in zip(ids,titles):
 s=next(x for x in t['scenes'] if x['id']==ident);chapters.append({'startSeconds':0 if ident in ['LF01','LF03'] else s['start'],'ko':s['title'],'en':title})
chapters.append({'startSeconds':t['seconds']-10,'ko':'멤버십 감사와 프로그래밍 과외 안내','en':'Membership thanks and programming coaching'})
assert all(int(b['startSeconds'])-int(a['startSeconds'])>=10 for a,b in zip(chapters,chapters[1:]))
def stamp(s):n=int(s);return f'{n//60:02}:{n%60:02}'
ko+='\n\n실제 게임40%·설명60%, 배경음악 없이 진행하는 강의입니다.\n\n챕터\n'+'\n'.join(stamp(c['startSeconds'])+' '+c['ko'] for c in chapters)
en+='\n\n40% actual gameplay and 60% explanation, narrated without background music.\n\nChapters\n'+'\n'.join(stamp(c['startSeconds'])+' '+c['en'] for c in chapters)
def file_record(path):
 f=ROOT/path;return {'path':path,'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}
video=file_record(f'output/{slug}/{slug}.captioned.mp4');video['seconds']=t['seconds'];assert video['sha256']==read(P/'production/current-pixel-review.json')['sha256']
record={'slug':slug,'status':'prepared-reviewed-local; actual Studio upload pending','video':video,'metadata':{'title':m['titles']['ko'],'description':ko,'privacyStatus':'private','language':'ko'},'englishMetadata':{'title':m['titles']['en'],'description':en,'language':'en-US','status':'pending'},'descriptionBody':{'ko':ko,'en':en},'subtitles':[{**file_record(f'output/{slug}/{slug}.{lang}.srt'),'language':lang,'status':'pending-platform-upload','cueCount':len(t['koCaptions'])} for lang in ['ko','en']],'thumbnail':{**file_record(f'projects/{slug}/publishing/thumbnail-v2.png'),'status':'prepared-reviewed; platform pending'},'videoId':None,'scheduled':False,'fullPublishingSettingsComplete':False,'humanListening':'pending','rightsReview':'Preserved recording permissions and Valve policy; game-IP/human review pending','baselinePreserved':'avLKKfQBV_U','chapters':chapters}
write(D/'youtube-upload.json',record)
subprocess.run(['node',str(ROOT/'scripts/prepare-youtube-upload.cjs'),slug],cwd=ROOT,check=True,creationflags=subprocess.CREATE_NO_WINDOW)
m['paths'].update(publishingKo=f'projects/{slug}/publishing/upload-description.ko.txt',publishingEn=f'projects/{slug}/publishing/upload-description.en.txt',audioReport=f'projects/{slug}/audio/mix-measurements.json',productionBuilder='production/batches/game-math-part2-teaching-revision/build-lines-episodes.py')
write(P/'project.json',m)
