from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[3];B=Path(__file__).parent
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
p=B/'progress-20261010.json';d=read(p)
d['quaternion'].update(narrationAsrReviewed=True,narrationAsrScope='33 v2 current-hash read-backs complete; raw numeric ambiguities N02/N05/N08 require clearer new retakes; no human listening approval',newExplanationScenesIncludingFraming=12,newGameNarrationScenes=15,secondAuxTtsJobs=30,secondAuxTtsGenerated=False,episodesPrepared=2,preservedOriginalAudit='quaternion-episode-flow-audit.json',newActualCandidateCapacitySeconds=509,measuredBridgeRenders=18,dotCrossPlacement='N06 immediately before original15 Hamilton product; next-explanation promise corrected without deleting original content')
state=read(Path('C:/Users/eazuo/renderformer/tmp/placement_focus_20261008/status.json'))
d['latestResearchSnapshot']={k:state.get(k) for k in ['status','time','owner_pid','job','completed','total']}
d['secondHandoffAttempt']={'token':'1b248f52-09ed-4c05-8894-8530dfd3a2d3','ttsStarted':False,'reason':'completed train_wireframe_head_42 validation explicitly reported non-finite checkpoint/loss; unchanged handoff gate rejected TTS','failedResearchMarker':'C:/Users/eazuo/renderformer/tmp/placement_focus_20261008/done/train_wireframe_head_42.json','checkpointSha256':'a9915665d8709f8318b1baea61dceabc69b50964a72570d4e14e13b27dd63be8','failurePreserved':True,'researchQueueRestoredAndFreshOwnerVerified':True,'resumedOwnerPid':64484,'history':'shared/output/gpu-handoff/1b248f52-09ed-4c05-8894-8530dfd3a2d3.json','pendingNextFamily':'train_wireframe_cnnA_42; wait in Node without blocking Python/GPU resource gate; unchanged handoff must validate that completed run too'}
d['sourceReview'].update(playedComparedCandidates=21,extraComparison='extra-source-playback-comparison.json',lastSelection='T506–522 replaces R501–516 for caption clearance; U616–642 follows inverse observation and motivates Hamilton product',secondManualAnnotationDraft='gb05-landmarks.json',secondManualAnnotationFinalApproval=False)
write(p,d)
extra=B/'extra-source-playback-comparison.json';r=read(extra)
r['nativeEndTimes'].update(T=16,U=32)
r['candidates']=[x for x in r['candidates'] if x['id'] not in ['T','U']]+[{'id':'T','source':'4Odvp_TIeQU','interval':[506,522],'chosen':[506,522],'beforeActionAfter':'approach ramp → airborne bicycle posture → landing and another bend','cameraOcclusionUi':'no original dialogue caption seen; following/banking camera and racer names preserved, body remains readable','reason':'prefer to R501–516 because game dialogue caption at503–505 can overlap fixed Korean caption band; retains clear torso, visible rear-wheel contour, jump and resulting travel'}, {'id':'U','source':'4Odvp_TIeQU','interval':[610,642],'chosen':[616,642],'rejected':[610,616],'beforeActionAfter':'fat-wheel bike emerges from jump, follows bends and passes gates before finish UI','cameraOcclusionUi':'opening enlarged wheel partly occludes torso; clearer selected road portion shows red vest, torso direction and visible wheel contour, HUD remains at edges','reason':'after inverse application, visible combined changes motivate composing two defined rotations; not an inference about game-internal operation order; reject initial wheel occlusion and later finish/results UI'}]
write(extra,r)
print(json.dumps({'research':d['latestResearchSnapshot'],'newTtsStarted':False,'originalMaterialChanged':False,'complete':False}))
