"""Record actual normal-speed playback and directly compared candidate pixels."""
from pathlib import Path
import json,datetime
ROOT=Path(__file__).resolve().parents[3];B=Path(__file__).parent;O=ROOT/'shared/output/game-math-part2-teaching-revision'
def read(p):return json.loads(p.read_text(encoding='utf8'))
fresh=read(O/'planes-fresh-official/native-playback.json');extra=read(O/'planes-extra-candidates/native-playback.json');secondary=read(O/'planes-portal-secondary/native-playback.json')
for evidence in [fresh,extra,secondary]:
 assert all(x['ended'] and x['rate']==1 for x in evidence)
rows=[
 {'game':'Human: Fall Flat','source':'human-fall-flat-steam-257175671','compared':[[0,54.12]],'rejected':[[0,54.12]],'reason':'Two-to-three-second promotional cuts, giant text and magnet-focused closeups interrupt a complete plane/triangle operation.20–24 shows a transparent bridge briefly but several cuts obscure a consistent surface and outcome.','pixels':'All four two-second sample sheets directly viewed.','cameraOcclusionUI':'Fake REC graphics and promo titles; players/props obscure bridge corners; viewpoint repeatedly switches.'},
 {'game':'Human: Fall Flat','source':'human-fall-flat-steam-257076768','compared':[[0,60]],'rejected':[[0,60]],'reason':'Cliff walks and38–40 ice sliding are brief; dark caves/crowds obscure edges.46–50 rope bridge bends and is not one rigid flat plane. No sustained three-corner address example.','pixels':'All four two-second sample sheets directly viewed.','cameraOcclusionUI':'Frequent cuts and promotional titles; crowded objects, foliage and bent bridge prevent a stable planar reference.'},
 {'game':'A Short Hike','source':'a-short-hike-steam-256755947','compared':[[0,54.52]],'rejected':[[0,54.52]],'reason':'Flight/climb montage is clear as traversal but does not reveal the exact surface-distance/address operation.34–39 ground is obscured by foliage and irregular rocks; no three unambiguous planar corners.','pixels':'All four two-second sample sheets directly viewed.','cameraOcclusionUI':'Frequent scene changes, credits and long closing title; foliage and character occlude the surface.'},
 {'game':'Noita','source':'N01','compared':[[686,736]],'rejected':[[686,736]],'reason':'Shop tooltips, descent banners and the dark fire-filled734–736 endpoint hide the ground; no stable complete plane example.','pixels':'Native whole excerpt plus734–736 fine samples directly viewed.','cameraOcclusionUI':'Shop UI/banners block terrain; projectiles/fire obscure before/action/after.'},
 {'game':'Noita','source':'N02','compared':[[920,963]],'rejected':[[920,963]],'reason':'Shop/banners/achievement followed by dark projectiles and partially visible ground. Brief clear pixels do not support the sustained exact surface question.','pixels':'Native whole excerpt plus952–963 fine samples directly viewed.','cameraOcclusionUI':'UI occupies terrain; quickly moving effects and camera hide surface edges.'},
 {'game':'Serious Sam 4','source':'S01','compared':[[344,371]],'rejected':[[344,371]],'reason':'Combat turns, mast/creature occlusion and only a two-second bridge view prevent stable three-corner surface tracking.','pixels':'Native whole excerpt plus detailed354–371 sequence directly viewed.','cameraOcclusionUI':'Weapon HUD retained; fast camera and foreground enemies conceal the useful surface.'},
 {'game':'Portal 2','source':'portal2-steam-5926','compared':[[0,116.33]],'tentative':[[34,41]],'rejected':[[0,34],[41,74],[78,116.33]],'reason':'34–41 shows launch through a plane and a landing with a finite platform. Most other shots are cinematic robot/button dialogue, montage or beams unrelated to this exact plane-distance/address question.','pixels':'Native whole source; two-second sheets02–07 directly viewed.','cameraOcclusionUI':'Dark first-person/platform edges and brief camera cuts limit capacity. No measured world values or engine internals inferred.'},
 {'game':'Portal 2','source':'portal2-steam-5786','compared':[[0,192.93]],'tentative':[[66,86],[86,104]],'rejected':[[0,64],[104,176]],'reason':'66–86 object pickup, wall opening and passage;86–104 crossing onto a walkway can demonstrate distinct surface patches. Long Wheatley dialogue and staircase/vegetation scenes do not teach one stable plane or triangle address.','pixels':'Native whole source; two-second sheets02–11 directly viewed.','cameraOcclusionUI':'Gun/held robot and railing occlude lower regions; carry only observed surface patches and reset at actual camera cuts.'}
]
record={'reviewedAt':datetime.datetime.now().astimezone().isoformat(),'nativeProofs':{'fresh':fresh,'extra':extra,'secondary':secondary},'candidates':rows,'selectionFinal':False,'chosenIntervals':[],'firstTimeClarityDecision':'Bright Portal gel/platform excerpts previously compared expose sustained surface/action/result more clearly than the new promotional montages. Fresh titles were reviewed and rejected on teaching evidence, not availability.','rights':'Official Portal primary Valve video policy recorded; publisher/IP and human listening review remain pending. Other developer policy unknown.','priorUse':'A Short Hike previously considered/rejected in camera/projection candidates; these Steam movie IDs have no found previous selected use. Human Fall Flat has no found prior source use.','noNarrationBasedOnUnselectedFootage':True}
(B/'planes-candidate-comparison.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print('Compared/rejected candidate intervals saved; tentative intervals require targeted pixel selection before narration.')
