from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,os,subprocess
ROOT=Path(__file__).resolve().parents[3];BASE=Path(__file__).parent/'revision-balatro60-v2'
read=lambda p:json.loads(p.read_text('utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
save=lambda p,j:p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n','utf-8')
proof=BASE/'source-content-adoption-v7.json';assert not proof.exists()
subprocess.run(['C:/Users/eazuo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node.exe','scripts/review-video-duplicates.cjs','presenting-game-scores','--check'],cwd=ROOT,check=True)
plan=read(BASE/'credit-composition-review-plan-v7.json');assert len(plan['boards'])==19 and plan['sourceSamplesReused']==110
for b in plan['boards']:
 assert sha(ROOT/b['path'])==b['sha256']
 for e in b['entries']:assert sha(ROOT/e['path'])==e['sha256']
 b['directlyRead']=True
source=ROOT/'shared/assets/presenting-game-scores/revision-balatro60-v2/longplay-c1WD4x9Dyg0.mp4'
assert sha(source)=='4f024be9da0ece4f3d1b9f19f840a46fccf431c4efcf0938d0bbf6ff253b8640'
now=datetime.now(timezone.utc).isoformat()
record={'schemaVersion':1,'adoptedAt':now,'sourcePath':source.relative_to(ROOT).as_posix(),'sourceSha256':sha(source),'descriptionCreditApproval':'projects/presenting-game-scores/production/revision-balatro60-v2/description-credit-approval-v1.json','descriptionLineKo':'플레이 녹화: Squeaky Whale Gameplay Archive — https://www.youtube.com/channel/UCoMF_6EsJYSq8vWG8zqRvtA','descriptionLineEn':'Gameplay recording: Squeaky Whale Gameplay Archive — https://www.youtube.com/channel/UCoMF_6EsJYSq8vWG8zqRvtA','compositionReview':plan,'all110ProxySamplesAnd19BoardsDirectlyRead':True,'normalPlaybackObserved':'Existing v3 playback observations plus current CUA v6 diamond window at1x muted; no claim that every intervening native frame was read','cuaFitProof':{'path':'shared/output/presenting-game-scores/revision-balatro60-v2/rights/native-credit-fit-v6.png','sha256':sha(ROOT/'shared/output/presenting-game-scores/revision-balatro60-v2/rights/native-credit-fit-v6.png')},'scope':'source content and native PTS intervals approved for dependent script writing; transformed proxy samples and native CUA fit support composition planning. All final encoded cues/cuts and continuous animation remain unapproved.','wholeNativeFrameReview':False,'nativePtsBoundsVerified':True,'observations':['Three sevens contribute51 chips; selected extra six contributes no visible chips.','Two Pair20×2 progresses to44×14 then hand616 and stable round616; transient482 not a final total.','Pair28×2 gives hand56, then round56.','Prior767 plus hand560 becomes stable round1327;1084 and261 are transient.','Full House40×4 progresses90×4, hand360 and round569.','Diamond Full House59×13 becomes767, still below target800.','Decimal mult70×8.50 gives595; stable round1699 after1104;1123 is transient.','Straight50×8 gives400 then stable round1104 after704;1093 is transient.','Two Pair64×11 gives704;680 is transient; target1200 remains unmet.','Debuffed diamond ten visibly crossed out and contributes no chips;64×7=448;388 is transient; exclude redraw/hover1409 onward.'],'cutMeaningReview':['Hand-selection views retained only to identify the labelled hand/input cards; no unrelated idle or menu quota.','No windows are presented as one continuous match, optimal strategy or a victory.','Tutorial, promotion, cashout and shop are excluded.'],'gameplayRatioStatus':'110seconds Balatro conditional allocation; final measured6:4 and body6:4 pending voice timing','footageAdoptedForScript':True,'sourceAudio':False,'loop':False,'slowdown':False,'finalCuePixelsApproved':False,'finalPublicRightsApproved':False,'humanListening':'pending','researchChanges':0,'newGitImages':0,'compositionOuterSession':76720,'compositionOuterExitObserved':0}
save(proof,record)
sources=BASE/'sources';sources.mkdir(exist_ok=True)
baseline=read(ROOT/'projects/presenting-game-scores/sources/game-candidates.json')
save(sources/'game-candidates.json',{'schemaVersion':1,'revision':'balatro60-tetris40-v2','baselineCandidatesPreserved':'projects/presenting-game-scores/sources/game-candidates.json','baselineSha256':sha(ROOT/'projects/presenting-game-scores/sources/game-candidates.json'),'sourceAdoption':proof.relative_to(ROOT).as_posix(),'chosen':[{'game':'Balatro','recorder':'Squeaky Whale Gameplay Archive','sourceUrl':'https://www.youtube.com/watch?v=c1WD4x9Dyg0','sourcePath':record['sourcePath'],'sha256':record['sourceSha256'],'recentUse':'Fresh longplay source for this revision; previous score baseline used only official press master; source IDs differ but content selection was directly reviewed','rights':'Actual displayed reuse conditions require visible credit and description channel link; specific user exception now approved; final public-rights review pending','cuts':plan['cuts'],'insertionChapters':['04','05','07','08','09','10']},{'game':'Tetris Effect: Connected','source':'Preserved official Classic/Modern Score Attack native action bank','concept':'Separate quantity from evaluation and opponent-relative point gap','sourceBank':'production/batches/sakurai-planning-game-design/proof-presenting-game-scores/source-action-bank-v4.json','insertionChapters':['02','03','06'],'selectedDurationPendingMeasuredTiming':True}],'rejected':[{'game':'Ballionaire','reason':'Available press montage insufficient unique action; no padding with trailer loops'},{'source':'Balatro Friends of Jimbo Pack3/4','reason':'Promotional montage, not a continuous hand calculation'},{'source':'Skoottie curated longplay','reason':'Playlist curation alone does not authorize recording reuse'},{'source':'Previous short Balatro official clips','reason':'Insufficient normal-speed duration for requested60% mix; preserve baseline locally'},{'game':'Hi-Fi Rush','reason':'Previous praise-player material; current requested two-game Balatro/Tetris mix takes precedence'}],'finalGameRatioApproved':False,'finalBodyRatioApproved':False,'publicRightsApproved':False})
pub=BASE/'publishing';pub.mkdir(exist_ok=True)
(pub/'description-credit.ko.txt').write_text(record['descriptionLineKo']+'\n','utf-8');(pub/'description-credit.en.txt').write_text(record['descriptionLineEn']+'\n','utf-8')
req=read(BASE/'request.json');req['checkpoints']['sourceSelected']=True;req['sourceContentAdoption']=proof.relative_to(ROOT).as_posix();req['stage']='source-content-approved-selective-script-revision';req['nextAction']='Revise only dependent KO/EN examples and observation guides, preserving unchanged PCM; final native/framed cue and ratio approval follows measured new narration.';save(BASE/'request.json',req)
cpPath=ROOT/'projects/presenting-game-scores/production/latest-checkpoint.json';cp=read(cpPath);cp.update(recordedAt=now,stage=req['stage'],revisionCheckpoints=req['checkpoints'],revisionSourceContent=req['sourceContentAdoption'],nextAction=req['nextAction'],ownedJob={'sessionId':76720,'exitCode':0,'workerExpectedRunning':False,'cpuThreads':2,'gpu':0});save(cpPath,cp)
qp=ROOT/'production/batches/sakurai-planning-game-design/queue.json';q=read(qp);item=next(x for x in q['items'] if x['slug']=='presenting-game-scores');item.update(stage=req['stage'],revisionCheckpoints=req['checkpoints'],revisionSourceContent=req['sourceContentAdoption'],nextAction=req['nextAction']);q['updatedAt']=now;q['lastProgressAt']=now;save(qp,q)
print('Source content approved for selective script revision; native whole-frame/final cues/ratios/public rights remain pending.')
