"""Prepare serial current-input ASS QA; baseline workers and outputs preserved."""
from pathlib import Path
P=Path(__file__).parent;dst=P/'build-revision-selected-input-preflight-v3.py';assert not dst.exists()
t=(P/'build-selected-input-preflight-v8.py').read_text('utf-8')
t=t.replace("selected-inputs-v8", "revision-balatro60-v2/selected-inputs-v3")
t=t.replace("BASE/'selected-input", "BASE/'revision-balatro60-v2/selected-input")
t=t.replace("preflight-v8", "preflight-v3").replace("execution-v8", "execution-v3")
t=t.replace("PLAN=BASE/'measured-timeline-candidate-v7.json'", "PLAN=BASE/'revision-balatro60-v2/measured-editorial-candidate-v3.json'")
t=t.replace("CAP=BASE/'caption-candidate-v8/captions.json'", "CAP=BASE/'revision-balatro60-v2/caption-candidate-v4/captions.json'")
t=t.replace("BASE/'measured-black-input-verification-v8.json'", "BASE/'revision-balatro60-v2/measured-black-input-verification-v3.json'")
t=t.replace("BASE/'measured-native-inputs-execution-v8.json'", "BASE/'revision-balatro60-v2/measured-native-inputs-execution-v1.json'")
t=t.replace('7334','7708').replace('7333','7707').replace('18332','19268').replace('18331','19267').replace('10999','11561')
t=t.replace("len(native['results'])==12", "len(native['results'])==18")
t=t.replace("len(s['segments'])==24", "len(s['segments'])==31")
t=t.replace('totalBlackSegments=12','totalBlackSegments=13').replace('total=12','total=13')
t=t.replace("koCueCount']==168", "koCueCount']==175").replace("enCueCount']==68", "enCueCount']==70")
t=t.replace('168','175').replace('en=68','en=70').replace('cuts=24','cuts=31').replace('blackSegments=12','blackSegments=13').replace('inputs=24','inputs=31')
t=t.replace('all24CutsCovered','all31CutsCovered').replace('all12BlackMotionSegmentsCovered','all13BlackMotionSegmentsCovered')
t=t.replace('reuse12 native','reuse18 verified native').replace('12Black','13Black')
t=t.replace('wholeBodyDecodeExitCode=0', 'wholeBodyDecodeExitCode=0')
dst.write_text(t,'utf-8');print('Prepared revision ASS input worker; no render/extraction performed.')
