"""Record directly reviewed source pixels, real Studio results and chapter comparison."""
from pathlib import Path
import json,hashlib,datetime,shutil
R=Path(__file__).resolve().parents[3];B=Path(__file__).parent;W=R/'shared/output/game-math-part2-full-series';P=B/'preflight';slug='game-math-mesh-uv'
def read(p):return json.loads(p.read_text(encoding='utf8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
export=Path('C:/Users/eazuo/AppData/Local/Temp/browser-use/exports/youtube--3NQEd_8mWg-2c6c46bb-51bc-4fa7-83b8-233853f599a0.txt')
transcript=R/'tmp/game-math-part2-sources/legacy-directx-uv--3NQEd_8mWg.transcript.txt'
shutil.copyfile(export,transcript)
proofs=[]
for name in ['studio-current-math-inventory.ax.txt','studio-uv-title-filter.ax.txt','studio-mesh-title-filter.ax.txt','studio-normal-title-filter.ax.txt']:
 p=W/'mesh-uv-preflight'/name; assert p.exists();proofs.append(dict(path=p.relative_to(R).as_posix(),sha256=sha(p)))
assert 'Sampler State·텍스처 UV·필터링' in (W/'mesh-uv-preflight/studio-uv-title-filter.ax.txt').read_text(encoding='utf8')
assert all('일치하는 동영상이 없습니다.' in (W/'mesh-uv-preflight'/n).read_text(encoding='utf8') for n in ['studio-mesh-title-filter.ax.txt','studio-normal-title-filter.ax.txt'])
comparison=dict(status='full-content-and-native-channel-reviewed-distinct',atUtc=now,target=slug,inventory='production/preflight/game-math-mesh-uv.json',studioProofs=proofs,
 legacy=dict(videoId='-3NQEd_8mWg',title='Sampler State·텍스처 UV·필터링 | DirectX 11',url='https://www.youtube.com/watch?v=-3NQEd_8mWg',transcript=transcript.relative_to(R).as_posix(),transcriptSha256=sha(transcript),transcriptReviewed='Complete0:00–13:43 generatedKO transcript; sampling/filter/mipmap and DirectX sampler creation/binding, with UV/address-mode discussion8:02–11:12.',overlap='UV names/normalized range and wrap/clamp/mirror concepts recur as prerequisites.',distinct='New full10.4–10.5 math lecture adds indexed memory/topology, complete normal accumulation/detach/angle weighting/inverse-transpose, exact UV mapping coordinates and interpolation-before-addressing/negative-floor failure exercise. No recreation of sampler API setup or filter/mipmap tutorial. Preserve existing upload.'),
 compared=[dict(slug='game-math-planes-barycentric',reason='Cross/plane normal and barycentric basics; no indexed storage, adjacency or full vertex normal construction.'),dict(slug='game-math-rendering-light',reason='Radiometry/reflection and unit-direction input; no mesh record construction, seam duplication or inverse-transpose computation.'),dict(slug='game-math-projection-depth',reason='Perspective/depth interpolation and pipeline; preserve its established correction rather than repeat fullw derivation.'),dict(slug='game-lighting-history-01',reason='Full relevant scene02 and normal-map/lightmap narratives inspected: historical lighting, Lambert angle and normal-map silhouettes, not indexed normals construction or exactUV repeat-order exercises. Preserve concurrent unfinished project.'),dict(videoIds=['wAomO97qcqM','WYUfapJHPJ4'],reason='Reviewed PART1 transform/inverse transcripts are prerequisites, not the full mesh/normal/UV surface-data question.')],
 decision='Distinct coherent full chapter; small prerequisite overlap is named, legacyDirectX API lesson preserved. Do not claim every term is new.')
write(P/'mesh-uv-content-duplicate-review.json',comparison)
generated=read(W/'inspection/mesh-uv-bigwalk-unused/generated-samples.json'); assert len(generated['records'])==12
notes={1:'200–260 green lit room, camera orbit and characters moving; clear black grid panel/frame, curved green wall, circular openings, rock and cylinder base. Grid is not asserted to be triangle topology.',2:'270–348 characters interact/move around green room and grid wall; surface patterns visible.350–375 confetti/chat/close character focus excluded from current cuts.',3:'580–706 yellow wall walk-through and moving characters/camera; flat faces, rounded opening outlines and wall thickness clearly visible.708+exit/environment excluded.',4:'810–834 red deck has visible flat plane/curved rail and control geometry;834–925 focuses on panorama and floating dialogue; not selected for current mesh/UV quota.'}
big=dict(status='all12fine-contact-sheets-directly-viewed-before-narration',atUtc=now,sourceId='wzQLP0Z3zII',sourceSha256=generated['sourceSha256'],sourceAudioUsed=False,sheets=[dict(**r,sha256=sha(R/r['sheet']),directlyViewed=True,note=notes[r['window']]) for r in generated['records']],priorUse='Existing rendering-light game and source. New cuts do not overlap its actual9source intervals; do not call a fresh title.',recordingPermissionProof='shared/output/game-math-part2-full-series/mesh-uv-preflight/bigwalk-recording-permission.ax.txt',implementationLimit='Visible surfaces/patterns/outline only; no hidden mesh, normal, address-mode or CSG assertion.')
write(P/'mesh-uv-bigwalk-fine-review.json',big)
index=read(B/'footage-index.json'); fine=read(P/'mesh-uv-sunset-fine-review.json'); source=R/fine['source']; assert sha(source)==fine['sourceSha256']
perm=W/'mesh-uv-preflight/sunset-recording-permission.ax.txt';assert 'Free to use Gameplay' in perm.read_text(encoding='utf8')
index['fN4iMYUyODc']=dict(id='fN4iMYUyODc',game='Sunset Overdrive',uploader='NCR Gameplay',url='https://www.youtube.com/watch?v=fN4iMYUyODc',file=fine['source'],sha256=fine['sourceSha256'],reviewedBeforeNarration=True,recordingPermissionObserved='Native description2026-10-09: Free to use Gameplay Recorded on PC,for your videos. Recording permission only; game-IP/publication review pending. No CC BY claim.',licenseLabel='uploader free-to-use recording statement',metadataProof=perm.relative_to(R).as_posix(),metadataSha256=sha(perm),sourceAudioUsed=False,priorUse='Exact title/source searches found no previous project use before mesh-uv authoring.',visibleAction='Actual full-screen real-time roof/wall traversal,visible vents,facades,window/brick/roof patterns and silhouette changes. No proprietary implementation inference.',inspection=['production/batches/game-math-part2-full-series/preflight/mesh-uv-sunset-fine-review.json'],publicGameIpReview='pending')
index['wzQLP0Z3zII'].setdefault('additionalReviews',{})[slug]=dict(atUtc=now,review='production/batches/game-math-part2-full-series/preflight/mesh-uv-bigwalk-fine-review.json',permissionProof=big['recordingPermissionProof'],history='Prior rendering-light source; current reviewed windows exclude all used intervals.')
write(B/'footage-index.json',index)
candidate=read(P/'mesh-uv-candidate.json');candidate['titleKo']='렌더링 ⑤ 메시·법선·UV';candidate['titleEn']='Rendering 5: Meshes, Normals and UVs';candidate['coverageStatus']='Full10.4–10.5 source and legacy tutorial compared; narrated full chapter prepared after directly reviewed real footage. Measured duration pending.'
write(B/'candidates'/f'{slug}.json',candidate)
print(json.dumps(dict(slug=slug,studioProofs=len(proofs),bigWalkFineSheets=12,legacyTranscriptReviewed=True,newSourceRegistered='fN4iMYUyODc'),ensure_ascii=False))
