"""Refine an unfinished full chapter at a complete point-to-pixel boundary.

Run after the owned initial numerical batch restores research. Preserve all
prepared scenes/audio and create only the current first episode; the second
remains an authored candidate until first-episode private/Git delivery.
"""
from pathlib import Path
import json,copy,hashlib,shutil,datetime
R=Path(__file__).resolve().parents[3];B=Path(__file__).parent;slug='game-math-camera-projection';second='game-math-projection-depth';P=R/'projects'/slug;W=R/'shared/output'/slug
def read(f):return json.loads(f.read_text(encoding='utf-8-sig'))
def write(f,v):f.parent.mkdir(parents=True,exist_ok=True);f.write_text(v if isinstance(v,str) else json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def sha(f):return hashlib.sha256(f.read_bytes()).hexdigest()
lease=R/'shared/output/GPU_HANDOFF.json'
assert not lease.exists() or read(lease).get('project')!=slug,'Finish this project’s current TTS before editing captured scripts. Preserve every foreign lease unchanged.'
handoff=read(R/'shared/output/gpu-handoff/a8b75499-3452-48ab-943d-783c4665df63.json');assert handoff['ttsExitCode']==0 and handoff['state']=='research_resume_verified'
assert read(W/'voice-job-result.json')['exitCode']==0
m=read(P/'project.json');assert not m.get('finalRender') and not (P/'publishing/youtube-upload.json').exists()
full=read(B/f'lessons/{slug}.json');assert len(full['scenes'])==24
baseline=W/'before-conceptual-episode-refinement';assert not baseline.exists();baseline.mkdir()
for f in [B/f'lessons/{slug}.json',P/'project.json',P/'script/narration.ko.json',P/'script/narration.en.json',P/'planning/coverage-audit.json',P/'sources/gameplay-cuts.json',P/'production/narration-review-in-progress.json',P/'production/narration-number-correction.json',W/'voice-job-result.json',W/'voice-job.log',R/'motion-canvas/src/projects'/slug/'project.ts']:
 shutil.copy2(f,baseline/f.name)
O=R/m['tts']['outputDir'];audio=[]
for s in full['scenes']:
 sid=s['id'];wav=O/f'chunks/{sid}-scene.wav';raw=O/f'asr/{sid}.json';assert wav.exists();shutil.copy2(wav,baseline/wav.name)
 if raw.exists():shutil.copy2(raw,baseline/f'{sid}.asr.json')
 audio.append(dict(scene=sid,wav=wav.relative_to(R).as_posix(),baselineWave=(baseline/wav.name).relative_to(R).as_posix(),wavSha256=sha(wav),rawAsrCurrent=raw.exists() and read(raw).get('audio_sha256')==sha(wav)))
by={s['id']:s for s in full['scenes']}
# More explicit cardinal and decimal speech repairs the observed1/2readbacks.
changes={('13',1):('가까운 평면 일과 먼 평면 십일은 유지합니다. 제트에 곱하는 계수는 일 점 이 영입니다. 그 결과에서 이 점 이 영을 뺀 뒤, 더블유로 나눕니다.','Keep near one and far eleven. The multiplier for view z is one point two zero. Subtract two point two zero from that result, then divide by w.'),('13',3):('영 점 육오에 숫자 하나를 더하면 일 점 육오입니다. 이 값을 둘로 나누면 영 점 팔이오입니다. 두 깊이 범위를 바꾸어 적어도 같은 위치를 가리킵니다.','Adding one to zero point six five gives one point six five. Dividing by two gives zero point eight two five. The two depth conventions describe the same position.'),('13',6):('직교 깊이는 더블유를 일로 유지하며 선형 변환합니다. 영부터 일인 범위에서는 제트에서 하나를 빼고, 그 결과를 십으로 나눕니다. 마이너스 일부터 일인 범위에서는 방금 구한 값을 두 배로 만든 뒤, 하나를 뺍니다.','Orthographic depth keeps w at one and changes linearly. For zero to one, subtract one from view z and divide by ten. For minus one to one, double that result and subtract one.'),('15',3):('가로는 먼저 정규화된 값에 하나를 더합니다. 그 결과를 둘로 나누고, 너비를 곱한 뒤 창의 시작 위치를 더합니다. 영 점 오는 창 너비의 사 분의 삼 위치입니다.','For horizontal position, add one to the normalized value, divide by two, multiply by the width, and add the window origin. Zero point five maps to three-quarters of the window width.'),('15',5):('세로는 먼저 하나에서 구 분의 사를 뺍니다. 위가 플러스였던 방향을 뒤집는 계산입니다. 높이 사백오십의 절반을 곱한 다음 오십을 더합니다.','For vertical position, subtract four ninths from one to reverse the upward-positive direction. Multiply by half of height four hundred fifty, then add fifty.')}
changes[('18',4)]=('분자의 평균에 들어갈 값은 영과 영 점 이오입니다. 평균은 영 점 일이오입니다. 하나를 여덟으로 나눈 값입니다. 분모에서는 일과 영 점 이오의 평균을 구합니다. 영 점 육이오이고, 다섯을 여덟으로 나눈 값입니다.','The numerator averages zero and zero point two five, giving zero point one two five, which is one divided by eight. The denominator averages one and zero point two five, giving zero point six two five, which is five divided by eight.')
for (sid,i),(ko,en) in changes.items():by[sid]['ko'][i]=ko;by[sid]['en'][i]=en
chapter=B/'chapter-sources/camera-projection-full.json';assert not chapter.exists();write(chapter,full)
first=copy.deepcopy(full);first['totalParts']=8;first['episodeSubtitle']='렌더링3편 · 좌표 변환과 클리핑';first['scenes']=[copy.deepcopy(s) for s in full['scenes'] if int(s['id'])<=15]
overview=first['scenes'][0];overview['ko'][3]='마지막으로 작은 출력 창의 위치와 크기까지 반영해서, 같은 한 점이 화면의 어디에 오는지 계산을 완성하겠습니다.';overview['en'][3]='Finally, include the origin and size of a smaller viewport and complete the calculation of where that same point appears on screen.';overview['beats'][3]='한 점의 최종 화면 위치';overview['formulas'][3]='clip → divide → viewport'
summary=dict(id='24',kind='explanation',title='한 점의 화면 좌표 계산을 마무리하기',mode='summary',ko=['같은 점의 기준을 로컬에서 세계와 카메라로 옮긴 뒤, 투영 행렬로 클립 좌표를 만들었습니다.','시야 경계에서 먼저 자르고 더블유로 나눈 뒤 출력 창에 놓으면, 우리 점은 가로 칠백과 세로 백칠십오에 옵니다.','다음 편에서는 저장된 깊이가 거리와 어떻게 다른지, 텍스처 보간에 더블유가 왜 다시 필요한지 알아보겠습니다.'],en=['We expressed the same point in local, world, and camera frames, then used the projection matrix to produce clip coordinates.','After clipping, division by w, and viewport mapping, our point appears at horizontal seven hundred and vertical one hundred seventy-five.','Next, examine how stored depth differs from distance and why texture interpolation still needs w.'],beats=['같은 점 / 로컬 → 세계 → 뷰','클리핑 → 나눗셈 → 화면(700,175)','다음: 깊이와 원근 보간'],formulas=['p_clip = p_local M V P','P_screen = (700,175)','저장 깊이 / u와w의 관계'])
first['scenes'].append(summary)
first['coverage']={k:[sid for sid in ids if sid in {s['id'] for s in first['scenes']} and sid!='24'] for k,ids in full['coverage'].items()};first['coverage']['episodeConclusion']=['24'];first['contract']['episodeScope']='Complete main point-to-pixel calculation and near clipping. Remaining depth/interpolation,projection-plane scaling,GPU/CPU checks and independent exercises are preserved in the following authored episode.'
first['episodeRefinement']=dict(chapterBlueprint=chapter.relative_to(R).as_posix(),followupSlug=second,boundary='The full worked point reachesviewport(700,175) at originalscene15; no algorithm is cut.',allSourceScenesPreserved=True)
second_data=copy.deepcopy(full);second_data.update(slug=second,part=4,totalParts=8,episodeSubtitle='렌더링4편 · 깊이와 원근 보간')
intro=dict(id='01',kind='explanation',title='나눈 뒤에도 깊이와 w가 필요한 이유',mode='overview',ko=['화면의 위치를 구했는데, 왜 깊이는 실제 거리와 다르고 더블유는 아직 필요할까요?','먼저 실제 게임의 겹치는 건물을 살펴보고, 저장된 깊이가 거리와 어떻게 달라지는지 계산하겠습니다.','이어서 기울어진 지붕 무늬를 예로, 텍스처 값을 원근에 맞춰 이어 주는 보간을 설명합니다.','마지막에는 출력 창을 바꾼 세 문제를 풀고, 어느 좌표 단계부터 오류를 찾아야 하는지 정리하겠습니다.'],en=['Once a screen position is known, why does stored depth differ from distance, and why do we still need w?','First, observe overlapping game buildings and calculate how stored depth changes with distance.','Then use slanted roof patterns to explain perspective-correct interpolation of texture values.','Finally, solve three viewport exercises and organize how to locate the first incorrect coordinate stage.'],beats=['화면 위치 다음: 깊이와 w','실제 겹침 → 저장 깊이','표면 무늬 → 원근 보간','세 연습 문제 → 단계별 검사'],formulas=['screen position / depth / attributes','d = 1.1 − 1.1/z','u = interp(u/w) / interp(1/w)','입력 하나 변경 / 첫 오류 추적'])
mapping={f'{i:02}':f'{i-14:02}' for i in range(16,25)};second_data['scenes']=[intro,*[dict(copy.deepcopy(by[old]),id=new,preparedSourceScene=old) for old,new in mapping.items()]];second_data['coverage']={k:[mapping[sid] for sid in ids if sid in mapping] for k,ids in full['coverage'].items()};second_data['coverage']['episodeOverview']=['01'];second_data['contract']['episodeScope']='Depth and perspective-correct attributes after the first complete pixel-position lecture,with all original scaling,pipeline,viewport practice and debugging explanations preserved.'
second_data['preparedNarration']={mapping[a['scene']]:dict(a,requiresNewWave=a['scene']=='18') for a in audio if a['scene'] in mapping};second_data['episodeRefinement']=dict(chapterBlueprint=chapter.relative_to(R).as_posix(),predecessorSlug=slug,sourceMapping=mapping,allOriginalParagraphsRetained=True,overviewRequiresNewApprovedVoice=True,numericDivisionClarificationScene='04',serialPrivateGitGateRequired=True)
assert len(first['scenes'])==16 and len(second_data['scenes'])==10
assert {s['id'] for s in full['scenes'][1:-1]}=={s['id'] for s in first['scenes'][1:-1]}|set(mapping)-{'24'}
write(B/f'lessons/{slug}.json',first);write(B/f'lessons/{second}.json',second_data)
candidate=read(B/f'candidates/{slug}.json');candidate.update(episodeBoundary=first['episodeRefinement']['boundary'],planningStatus='Split at complete main calculation after measured full draft approached25minutes; current first episode voice/timing/private delivery pending.');write(B/f'candidates/{slug}.json',candidate);write(P/'planning/candidate.json',candidate)
second_candidate=dict(slug=second,titleKo='렌더링 ④ 나눈 뒤에도 필요한 깊이와 w',titleEn='Rendering 4: Depth and w After the Perspective Divide',viewerQuestion='화면 좌표를 나눈 뒤에도 왜w가 텍스처 보간에 필요하고 저장된 깊이는 거리와 어떻게 다를까?',sourceNotion=candidate['sourceNotion'],sections=['10.3.3','10.3.5','10.3.6'],episodeBoundary='Complete depth/interpolation worked example,all three independent viewport exercises and debugging conclusion.',planningStatus='Authored from preserved full-chapter material; first episode private/Git delivery and fresh duplicate/Studio review required before project creation.');write(B/f'candidates/{second}.json',second_candidate)
m['lecture'].update(totalParts=8,contract=first['contract']);m['editing']['openingOverview'].update(orderedSteps=overview['beats'][1:],narrationSeconds=None,reviewedBeforeTts=True);m['lecture']['episodeRefinement']=first['episodeRefinement'];write(P/'project.json',m)
for lang in ['ko','en']:write(P/f'script/narration.{lang}.json',dict(title=m['titles'][lang],scenes=[dict(id=s['id'],title=s['title'],lines=s[lang]) for s in first['scenes']]))
cuts=read(P/'sources/gameplay-cuts.json');cuts['cuts']=[c for c in cuts['cuts'] if int(c['scene'])<=15];write(P/'sources/gameplay-cuts.json',cuts)
coverage=read(P/'planning/coverage-audit.json');coverage.update(coverage=first['coverage'],contract=first['contract'],scope='First complete point-to-pixel episode; complementary depth/interpolation/practice paragraphs retained verbatim in the following authored episode.',chapterBlueprint=chapter.relative_to(R).as_posix(),followupSlug=second);write(P/'planning/coverage-audit.json',coverage)
write(P/'planning/outline.md','# 전체 강의 흐름\n\n'+'\n'.join(f'- {s["id"]} {s["kind"]}: {s["title"]}' for s in first['scenes'])+'\n\n실측 약25분 초안은 화면좌표 계산이 완성되는 경계에서 두 독립 영상으로 나눈다. 다음 편의 모든 원문 개념·예제는 보존한다. 각 편은 원본2초 도입·별도 전체 안내·결론·원본10초 회원 엔딩, 실제40%/설명60%, KO/EN 고정 하단 자막과 비공개/Git 검수를 갖춘다. 반복·느리게 재생·알고리즘 중간 절단 없음.\n')
mc=R/'motion-canvas/src/projects'/slug;imports=["import {makeProject} from '@motion-canvas/core';","import audio from './assets/final-mix.wav';"];entries=[('intro','brand-intro'),*[(f's{s["id"]}',f'scene{s["id"]}') for s in first['scenes']],('outro','membership-outro')]
for var,file in entries:imports.append(f"import {var} from './scenes/{file}?scene';")
write(mc/'project.ts','\n'.join(imports)+f"\nexport default makeProject({{name:'{slug}',audio,scenes:[{','.join(v for v,_ in entries)}]}});\n")
review=read(P/'production/narration-review-in-progress.json');review['scenes']=[s for s in review['scenes'] if s['scene'] in {x['id'] for x in first['scenes']} and s['scene'] not in ['01','13','15','24']];review['pendingScenes']=['01','13','15','24'];review['status']='conceptual-episode-refinement-current-overview-number-lines-and-summary-retakes-required';write(P/'production/narration-review-in-progress.json',review)
corr=read(P/'production/narration-number-correction.json');corr['preservedMovedRetakeScenes']=[x for x in corr['audioReplacements']['scenes'] if x['scene'] in ['17','18']];corr['retakeScenes']=['01','10','12','13','15','24'];corr['audioReplacements']['scenes']=[x for x in corr['audioReplacements']['scenes'] if x['scene'] in corr['retakeScenes']]
for sid in ['01','13','15']:
 row=next(x for x in corr['audioReplacements']['scenes'] if x['scene']==sid);row.pop('currentWaveSha256',None);row.pop('review',None)
corr['audioReplacements']['scenes'].append(dict(scene='24',originalWaveSha256=sha(O/'chunks/24-scene.wav')));corr['audioReplacements']['status']='pending-episode-overview-closure-and-natural-cardinal-number-repairs';corr['episodeRefinement']=first['episodeRefinement'];write(P/'production/narration-number-correction.json',corr)
qf=B/'queue.json';q=read(qf);idx=next(i for i,x in enumerate(q['items']) if x['slug']==slug);assert q['executionControl']['currentVideo']==slug and not any(x['slug']==second for x in q['items']);old=copy.deepcopy(q['items'][idx]);q['items'][idx].update(totalParts=8,status='conceptual-split-first-episode-narration-repair-in-progress')
for item in q['items'][idx+1:]:
 item['order']+=1
 if item.get('chapter')==10:item['part']+=1;item['totalParts']=8
q['items'].insert(idx+1,dict(order=old['order']+1,slug=second,chapter=10,part=4,totalParts=8,titleKo=second_candidate['titleKo'],titleEn=second_candidate['titleEn'],viewerQuestion=second_candidate['viewerQuestion'],sections=second_candidate['sections'],sourceNotion=second_candidate['sourceNotion'],status='queued-authored-from-preserved-chapter',preflightComplete=False,renderComplete=False,privateUploadComplete=False,gitDelivered=False));q.setdefault('episodeRefinementHistory',[]).append(dict(atUtc=datetime.datetime.now(datetime.timezone.utc).isoformat(),original=old,result=[slug,second],reason='Measured full10.3draft approached25minutes. Split after the complete main point reachesviewport700175; retain all depth/interpolation/scaling/pipeline/exercise/debugging scenes in independent next episode. No useful explanation cut or padding.',baseline=baseline.relative_to(R).as_posix()));write(qf,q)
plan=dict(status='applied-first-episode-voice-and-final-timing-pending',sourceChapter=chapter.relative_to(R).as_posix(),sourceChapterSha256=sha(chapter),baseline=baseline.relative_to(R).as_posix(),originalAudio=audio,episode1=dict(slug=slug,sourceScenes=[s['id'] for s in first['scenes']],newNarrationScenes=['01','13','15','24'],sourceCapacitySeconds=sum(s.get('maxSeconds',0) for s in first['scenes'])),episode2=dict(slug=second,sourceMapping=mapping,sourceCapacitySeconds=sum(s.get('maxSeconds',0) for s in second_data['scenes']),additionalInspectedReserve={'sourceId':'FRfnXAIbA-M','in':1340,'out':1360,'inspection':'production/batches/game-math-part2-full-series/preflight/camera-projection-source-extensions.json','selected':False,'purpose':'Available only if final second-episode minimum narration requires more unique roof-pattern footage; inspect exact final cut pixels.'}),allOriginalNonOverviewAndNonConclusionParagraphsPreserved=True,privateGitSerialGate=True,estimatedRuntime='Planning only: first about16minutes, second about11minutes. Refine after new overview/closure/numerical line narration; do not pad short episodes.')
write(B/'preflight/camera-projection-episode-refinement.json',plan);write(P/'planning/episode-refinement.json',plan);print('Preserved full chapter/audio; current16-scene main-chain episode and next10-scene depth/practice candidate authored. New approved voice and final QA required.')
