import {emptyBoard,canPlace,clearRows,rotate,createGame,defaultMove,lock,scenario} from './engine.js';
const $=s=>document.querySelector(s),catalog=await(await fetch('/api/catalog')).json();
let mode='cpp',game=createGame(),move=(dx,dy)=>defaultMove(game,dx,dy),clear=clearRows,turn=rotate,sequence=0,polling=false;
let ball={x:530,y:220,vx:2.4,vy:4.2},paddle={x:445,width:170},bricks=[],running=false,lastTime=0,debug=false,stepper=null;
const log=t=>{$('#output').textContent=(t+'\n'+$('#output').textContent).slice(0,600);};
window.audit=[];const audit=(type,data)=>window.audit.push({at:performance.now()/1000,type,...data});
function options(){const keys=mode==='cpp'?Object.keys(catalog.cpp):mode==='blocks'?['data','movement','buggy','rotation','clear','tests']:['breakout'];$('#lesson').innerHTML=keys.map(k=>`<option>${k}</option>`).join('');$('#editor').value=(mode==='cpp'?catalog.cpp:catalog.js)[keys[0]];$('#filename').textContent=mode==='cpp'?'lesson.cpp':mode==='blocks'?'blocks.js':'breakout.js';}
function selectMode(m){mode=m;document.body.classList.remove('full');$('#mode-title').textContent={cpp:'연결 리스트',blocks:'낙하 블록',breakout:'벽돌 깨기'}[m];$('#watch').style.display=m==='cpp'?'block':'none';$('#play-area').style.display=m==='cpp'?'none':'block';$('#controls').style.display=m==='cpp'?'none':'flex';$('#scenarios').style.display=m==='cpp'?'none':'flex';$('#runtime-title').textContent=m==='cpp'?'실행 중 변수':'실제 입력 · 플레이테스트';$('#source-note').textContent=m==='cpp'?'실제 MSVC 컴파일 · inspect 중단점에서 실행을 멈추는 계측 디버거':'편집한 함수를 실제 게임 런타임에 적용 · 시나리오는 재현 가능한 테스트 입력';options();reset();audit('mode',{mode});}
function reset(){game=createGame();move=(dx,dy)=>defaultMove(game,dx,dy);clear=clearRows;turn=rotate;ball={x:530,y:230,vx:2.4,vy:4.2};paddle={x:445,width:170};bricks=Array.from({length:30},(_,i)=>({x:85+(i%10)*90,y:80+Math.floor(i/10)*38,alive:true}));running=mode==='breakout';$('#status').textContent='준비';log('새 실행 상태');audit('reset',{mode});}
function observe(e){if(e.type==='breakpoint'){$('#status').textContent='중단: '+e.label;$('#watch').innerHTML=`<div>head = ${e.head}</div><div>current = ${e.current}</div><table><tr><th>value</th><th>address</th><th>next</th></tr>${e.nodes.map(n=>`<tr class="${n.address===e.current?'changed':''}"><td>${n.value}</td><td>${n.address}</td><td>${n.next}</td></tr>`).join('')}</table>`;log('실행 일시정지 · '+e.label);}else if(e.type==='build'){log('cl.exe exit '+e.exitCode+'\n'+e.text);$('#status').textContent=e.exitCode===0?'실행 중':'빌드 실패';}else if(e.type==='exit'){$('#status').textContent='종료 코드 '+e.exitCode;log('process exit '+e.exitCode);}else log(e.text);audit('process',e);}
async function poll(){if(polling)return;polling=true;try{const data=await(await fetch('/api/events?after='+sequence)).json();for(const e of data.events){sequence=e.sequence;observe(e);}}finally{polling=false;}}
await fetch('/api/stop');
setInterval(()=>{if(mode==='cpp')poll();},120);
async function run(){const code=$('#editor').value;audit('source-execute',{mode,code});if(mode==='cpp'){sequence=0;$('#watch').innerHTML='';await fetch('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});await poll();return;}
try{if(code.includes('const board')&&code.includes('const position')){let model;model=new Function('canPlace',code+';return {board,cells,position,move};')((cells,pos)=>canPlace(model.board,cells,pos.x,pos.y));game=createGame();game.board=model.board;game.cells=model.cells;game.x=model.position.x;game.y=model.position.y;move=(dx,dy)=>{model.position.x=game.x;model.position.y=game.y;model.board=game.board;model.cells=game.cells;const before={...model.position};model.move(dx,dy);game.x=model.position.x;game.y=model.position.y;return before.x!==game.x||before.y!==game.y;};log('소스에서 생성: board[16][10] · cells 4 · position (3,0)');}
else if(code.includes('function move'))move=new Function('game','canPlace',code+';return move;')(game,(cells,x,y)=>canPlace(game.board,cells,x,y));else if(code.includes('function clearRows'))clear=new Function(code+';return clearRows;')();else if(code.includes('function rotate'))turn=new Function(code+';return rotate;')();else if(code.includes('const results')){const results=new Function('clearRows','emptyBoard','canPlace',code)(clear,emptyBoard,(cells,x,y)=>canPlace(game.board,cells,x,y));log(results.map(r=>(r.passed?'PASS':'FAIL')+' '+r.name).join('\n'));audit('tests',{results});}else if(code.includes('function bounce'))window.bounce=new Function(code+';return bounce;')();
$('#status').textContent='편집한 코드 적용됨';log('현재 소스 실행 완료');}catch(e){log(String(e));$('#status').textContent='실행 오류';}}
function debugStep(){if(!stepper)return;const r=stepper.next();if(r.done){stepper=null;log('함수 종료: '+r.value);$('#status').textContent='단계 실행 종료';audit('debug-end',{value:r.value,state:structuredClone(game)});}else{log(`중단점 ${r.value.line}행: x=${r.value.x}, y=${r.value.y}, width=${r.value.width}\ncandidate=${JSON.stringify(r.value.candidate)}, current valid=${r.value.valid}`);$('#status').textContent=`${r.value.line}행 · x=${r.value.x}, y=${r.value.y}`;audit('debug-stop',r.value);}}
function input(action){if(mode==='breakout'){if(action==='left')paddle.x=Math.max(70,paddle.x-45);if(action==='right')paddle.x=Math.min(810,paddle.x+45);if(action==='drop')running=!running;audit('paddle-input',{action,paddle:{...paddle},ball:{...ball}});return;}
if(debug&&['left','right','down'].includes(action)&&$('#editor').value.includes('function move')){const code=$('#editor').value.split('\n').map((l,i)=>{if(/game\.[xy] (?:\+=|=)|const candidate|return/.test(l))return `yield {line:${i+1},x:game.x,y:game.y,width:10,candidate:(()=>{try{return candidate}catch{return null}})(),valid:canPlace(game.cells,game.x,game.y)};\n`+l;return l;}).join('\n').replace('function move','function* move');const f=new Function('game','canPlace',code+';return move;')(game,(cells,x,y)=>canPlace(game.board,cells,x,y));stepper=f(action==='left'?-1:action==='right'?1:0,action==='down'?1:0);audit('debug-input',{action,code:$('#editor').value});debugStep();return;}
const before={x:game.x,y:game.y,cells:game.cells.map(c=>[...c]),cleared:game.cleared};let ok=true;
if(action==='left')ok=move(-1,0);if(action==='right')ok=move(1,0);if(action==='down')ok=move(0,1);if(action==='rotate'){const cells=turn(game.cells);ok=canPlace(game.board,cells,game.x,game.y);if(ok)game.cells=cells;}if(action==='drop'){let n=0;while(move(0,1)&&n++<20){}lock(game,clear);}if(!ok){game.rejected++;game.last='검사 실패 · 위치 확인';}else if(action!=='drop')game.last='입력 반영';$('#status').textContent=`(${game.x}, ${game.y}) · ${ok?'허용':'거부'}`;log(`${action}: (${before.x},${before.y}) → (${game.x},${game.y}) / ${ok?'true':'false'}`);audit('game-input',{action,before,after:structuredClone(game),accepted:ok});}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>selectMode(b.dataset.mode));$('#lesson').onchange=()=>{$('#editor').value=(mode==='cpp'?catalog.cpp:catalog.js)[$('#lesson').value];audit('open-source',{file:$('#lesson').value});};$('#blank').onclick=async()=>{if(mode==='cpp'){await fetch('/api/stop');sequence=0;$('#watch').innerHTML='실행할 노드가 없습니다.';$('#output').textContent='';$('#status').textContent='새 파일';}$('#editor').value=mode==='cpp'?catalog.cpp.blank:'';audit('new-file',{mode});};$('#editor').oninput=()=>audit('edit',{mode,length:$('#editor').value.length});$('#run').onclick=run;$('#debug').onclick=()=>{debug=!debug;$('#debug').textContent=debug?'중단점 끄기':'중단점 켜기';audit('breakpoints',{enabled:debug});};$('#step').onclick=async()=>{if(mode==='cpp')await fetch('/api/step');else debugStep();audit('step',{});};$('#reset').onclick=reset;$('#view-toggle').onclick=()=>{document.body.classList.toggle('full');audit('view',{full:document.body.classList.contains('full')});};document.querySelectorAll('[data-input]').forEach(b=>b.onclick=()=>input(b.dataset.input));document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{const name=b.dataset.scenario;if(mode==='breakout'){ball={x:name==='paddle-edge'?paddle.x+15:paddle.x+paddle.width/2,y:460,vx:0,vy:4};running=true;}else scenario(game,name);log('재현 입력: '+name);audit('scenario',{name,state:structuredClone(game)});});
window.addEventListener('keydown',e=>{if(e.target===$('#editor'))return;const keys={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',' ':'drop'};if(keys[e.key]){e.preventDefault();input(keys[e.key]);}});
const ctx=$('#game').getContext('2d'),colors=['#fff','#2f5faa','#bb6a45','#527b65','#b27caa','#e0b743'];
function draw(t){const dt=lastTime?Math.min((t-lastTime)/16.666,2):1;lastTime=t;ctx.clearRect(0,0,1050,750);ctx.fillStyle='#f4f6f9';ctx.fillRect(0,0,1050,750);
if(mode==='blocks'){const cell=37,left=340,top=38;ctx.fillStyle='#fff';ctx.fillRect(left,top,370,592);for(let y=0;y<16;y++)for(let x=0;x<10;x++){ctx.strokeStyle='#dce2ea';ctx.strokeRect(left+x*cell,top+y*cell,cell,cell);if(game.board[y][x]){ctx.fillStyle=colors[game.board[y][x]];ctx.fillRect(left+x*cell+2,top+y*cell+2,cell-4,cell-4);}}for(const[dx,dy]of game.cells){ctx.fillStyle='#2f5faa';ctx.fillRect(left+(game.x+dx)*cell+2,top+(game.y+dy)*cell+2,cell-4,cell-4);ctx.fillStyle='#5f89bd';ctx.fillRect(left+(game.x+dx)*cell+4,top+(game.y+dy)*cell+4,cell-8,5);}ctx.font='28px Malgun Gothic';ctx.fillStyle='#24384f';ctx.fillText('낙하 블록',65,105);ctx.font='23px Malgun Gothic';ctx.fillText('← → 이동',65,165);ctx.fillText('↑ 회전 · ↓ 한 칸',65,205);ctx.fillText('SPACE 고정',65,245);ctx.fillText('지운 줄 '+game.cleared,765,135);ctx.fillText('놓은 블록 '+game.placed,765,180);ctx.fillText('거부 '+game.rejected,765,225);ctx.fillText(game.last,340,682);}
if(mode==='breakout'){if(running){ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<70||ball.x>980)ball.vx*=-1;if(ball.y<55)ball.vy=Math.abs(ball.vy);if(ball.vy>0&&ball.y>606&&ball.y<638&&ball.x>=paddle.x&&ball.x<=paddle.x+paddle.width){(window.bounce||((b,p)=>{const offset=(b.x-(p.x+p.width/2))/(p.width/2);b.vx=offset*5;b.vy=-Math.sqrt(36-b.vx*b.vx);}))(ball,paddle);audit('paddle-collision',{ball:{...ball},paddle:{...paddle}});}for(const b of bricks){if(b.alive&&ball.x>b.x&&ball.x<b.x+80&&ball.y>b.y&&ball.y<b.y+27){b.alive=false;ball.vy*=-1;audit('brick-hit',{x:b.x,y:b.y});break;}}if(ball.y>735){ball={x:530,y:300,vx:1.5,vy:4};audit('ball-reset',{});}}ctx.fillStyle='#dce4ee';ctx.fillRect(60,45,6,665);ctx.fillRect(984,45,6,665);for(const b of bricks)if(b.alive){ctx.fillStyle=colors[1+Math.floor(b.y/38)%5];ctx.fillRect(b.x,b.y,80,27);}ctx.fillStyle='#2f5faa';ctx.fillRect(paddle.x,620,paddle.width,18);ctx.beginPath();ctx.arc(ball.x,ball.y,13,0,Math.PI*2);ctx.fillStyle='#bc653f';ctx.fill();ctx.font='23px Malgun Gothic';ctx.fillStyle='#24384f';ctx.fillText('← → 패들 이동 · SPACE 일시정지',80,740);}
requestAnimationFrame(draw);}
window.workbench={getMode:()=>mode,getGame:()=>structuredClone(game),getCatalog:()=>catalog,selectMode,run,input};selectMode('cpp');requestAnimationFrame(draw);
