// Educational demonstrations. C++ text is saved, built by MSVC, and executed.
const prefix='struct Node {\n    int value;\n    Node* next;\n};\n#define OWN_NODE\n#include "trace.hpp"\n\n';
const cpp={
 blank:'int main()\n{\n\n}\n',
 node:prefix+'int main() {\n    Node* head = nullptr;\n    inspect("empty head", head);\n    head = new Node{10, nullptr};\n    inspect("first node", head, head);\n    printList(head);\n    destroy(head);\n}\n',
 pair:prefix+'int main() {\n    Node* head = new Node{10, nullptr};\n    inspect("first node", head, head);\n    head->next = new Node{20, nullptr};\n    inspect("two nodes", head, head->next);\n    for (Node* current = head; current; current = current->next) {\n        inspect("traversal", head, current);\n        std::cout << current->value << std::endl;\n    }\n    inspect("loop ended", head, nullptr);\n    printList(head);\n    destroy(head);\n}\n',
 insert:prefix+'int main() {\n    Node* head = new Node{10, new Node{20, nullptr}};\n    inspect("before insertion", head, head);\n    Node* added = new Node{15, head->next};\n    inspect("old next preserved", head, added);\n    head->next = added;\n    inspect("inserted 15", head, added);\n    printList(head);\n    Node* another = new Node{17, added->next};\n    added->next = another;\n    inspect("inserted 17", head, another);\n    printList(head);\n    destroy(head);\n}\n',
 remove:prefix+'void removeHead(Node*& head) {\n    if (!head) return;\n    Node* removed = head;\n    head = head->next;\n    delete removed;\n}\nint main() {\n    Node* head = new Node{10, new Node{15, new Node{20, nullptr}}};\n    inspect("before middle deletion", head, head->next);\n    Node* removed = head->next;\n    head->next = removed->next;\n    delete removed;\n    inspect("middle deleted", head);\n    removeHead(head);\n    inspect("head deleted", head);\n    removeHead(head);\n    inspect("only node deleted", head);\n    removeHead(head);\n    inspect("empty case safe", head);\n    printList(head);\n}\n',
 tail:prefix+'void append(Node*& head, int value) {\n    Node* added = new Node{value, nullptr};\n    if (!head) { head = added; return; }\n    Node* tail = head;\n    while (tail->next) tail = tail->next;\n    tail->next = added;\n}\nint main() {\n    Node* head = nullptr;\n    inspect("start empty", head);\n    append(head, 7);\n    inspect("append to empty", head);\n    append(head, 21);\n    inspect("append to nonempty", head);\n    append(head, 42);\n    inspect("third append", head);\n    printList(head);\n    destroy(head);\n}\n'
};
const js={
 data:'const board = Array.from({length: 16}, () => Array(10).fill(0));\nconst cells = [[0, 0], [1, 0], [2, 0], [1, 1]];\nconst position = {x: 3, y: 0};\n\nfunction move(dx, dy) {\n  const candidate = {x: position.x + dx, y: position.y + dy};\n  if (canPlace(cells, candidate)) Object.assign(position, candidate);\n}\n',
 movement:'function move(dx, dy) {\n  const candidate = {x: game.x + dx, y: game.y + dy};\n  if (canPlace(game.cells, candidate.x, candidate.y)) {\n    game.x = candidate.x;\n    game.y = candidate.y;\n    return true;\n  }\n  return false;\n}\n',
 buggy:'function move(dx, dy) {\n  game.x += dx;\n  game.y += dy;\n  return canPlace(game.cells, game.x, game.y);\n}\n',
 rotation:'function rotate(cells) {\n  const turned = cells.map(([x, y]) => [-y, x]);\n  const minX = Math.min(...turned.map(c => c[0]));\n  const minY = Math.min(...turned.map(c => c[1]));\n  return turned.map(([x, y]) => [x - minX, y - minY]);\n}\n',
 clear:'function clearRows(board) {\n  const kept = board.filter(row => !row.every(cell => cell !== 0));\n  const cleared = board.length - kept.length;\n  while (kept.length < board.length) {\n    kept.unshift(Array(board[0].length).fill(0));\n  }\n  return {board: kept, cleared};\n}\n',
 tests:'const results = [];\nfunction check(name, actual, expected) {\n  results.push({name, passed: JSON.stringify(actual) === JSON.stringify(expected)});\n}\ncheck("empty board", clearRows(emptyBoard()).cleared, 0);\ncheck("right wall", canPlace([[0,0]], 10, 0), false);\nconst two = emptyBoard();\ntwo[14].fill(1); two[15].fill(1);\ncheck("two adjacent rows", clearRows(two).cleared, 2);\nreturn results;\n',
 breakout:'function bounce(ball, paddle) {\n  const offset = (ball.x - (paddle.x + paddle.width / 2)) / (paddle.width / 2);\n  ball.vx = offset * 5;\n  ball.vy = -Math.sqrt(36 - ball.vx * ball.vx);\n}\n'
};
module.exports={cpp,js};
