// Record verified BODY deliverables without claiming publishing/outro approval.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../../..'),project=path.join(root,'projects/small-window-game-design'),work=path.join(__dirname,'full-v2');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,s)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof s==='string'?s:JSON.stringify(s,null,2)+'\n');};
const mf=path.join(project,'project.json'),m=read(mf),plan=read(path.join(work,'plan.json')),qa=read(path.join(work,'qa.json')),layout=read(path.join(work,'caption-layout-qa.json')),editor=read(path.join(work,'editor-playback-qa.json'));
const ko=read(path.join(project,'script/narration.ko.json')),en=read(path.join(project,'script/narration.en.json'));
if(qa.videos.videoClean.frames!==plan.totalFrames||editor.sceneCount!==6)throw Error('QA mismatch');
m.status='body-rendered-awaiting-outro-and-publication-review';m.publishReady=false;
m.titles={ko:ko.title,en:en.title};m.video.durationSeconds=+plan.seconds.toFixed(3);
m.production={...m.production,timingIsMeasured:true,previewOnly:false,bodyOnly:true,bodySeconds:plan.seconds};
m.editing={...m.editing,timingStatus:'measured-v2',actualGameplaySeconds:plan.gameplaySeconds,actualGameplayShare:plan.gameplayShare,actualExplanationSeconds:plan.diagramFrames/60,captionTextMaxWidth:1050,captionCenterY:970};
m.audio.mixStatus='body-mixed-verified-awaiting-human-listening';m.audio.sourceAudioPublicationReview='pending-third-party-music-check';
m.paths.editorAudioMix='motion-canvas/src/projects/small-window-game-design/assets/final-mix.wav';
m.paths.captionEditable='projects/small-window-game-design/production/full-v2/captions.ko.ass';
m.approvals.finalListening='pending-human-review';m.voicePreview.voiceApproval='approved-by-follow-up-production-request';
m.finalRender={kind:'full-body',qa:'projects/small-window-game-design/production/full-v2/qa.json',frames:plan.totalFrames,seconds:plan.seconds,captionCueCount:layout.cues.length,knownIssues:[
  '원본 회원 사진·이름·배지 이미지 미확보로 10초 멤버십 엔딩은 아직 포함하지 않았습니다.',
  '전체 청취와 게임 원음의 제3자 음악 권리 검토 전에는 게시 승인본이 아닙니다.'
]};write(mf,m);
const chapter=s=>`${String(Math.floor(s.start/60)).padStart(2,'0')}:${String(Math.floor(s.start)%60).padStart(2,'0')}`;
const credits=`\n\nGameplay\nNo Copyright Gameplay — https://www.youtube.com/NoCopyrightGameplays\nForza Horizon 5: https://www.youtube.com/watch?v=ZnCxVxfv3MM\nDOOM: https://www.youtube.com/watch?v=YANZzc_bHSU\n\nForza Horizon 5 footage: © Microsoft Corporation. Created under Microsoft's Game Content Usage Rules (https://www.xbox.com/en-US/developers/rules). Not endorsed by or affiliated with Microsoft.\nDOOM fan video policy: https://bethesda.net/en-NZ/news/bethesda-video-policy\n\nMusic\n'Discovery' by Scott Buckley - released under CC-BY 4.0. www.scottbuckley.com.au\nhttps://www.scottbuckley.com.au/library/discovery/\nLicense: https://creativecommons.org/licenses/by/4.0/\n\nConcept reference\nhttps://www.youtube.com/watch?v=DGIJk0Uh8jU\n`;
write(path.join(project,'publishing/youtube.ko.md'),`# ${ko.title}\n\n같은 게임도 화면에 무엇을 얼마나 담느냐에 따라 다르게 느껴집니다.\n화면 비율, 시야각(FOV), 대상의 화면 점유율은 어떻게 다를까요?\n\n16:9와 21:9 비교, 넓은 FOV와 작은 표적의 절충, 운전석·무기·UI가 가리는 공간을 살펴봅니다.\nForza Horizon 5와 DOOM은 게임 디자인을 설명하는 사례이며, 비교 도식은 직접 만든 2.5D 설명용 장면입니다. 실제 게임의 카메라 설정을 변경해 측정한 결과가 아닙니다.\n\n중요한 것은 모든 것을 크게 보여주는 것이 아니라, 지금 보고 판단하고 행동할 단서를 잘 보여주는 것입니다.\n한국어 내레이션 · 한국어/영어 자막\n\n## 챕터\n${plan.scenes.map(s=>`${chapter(s)} ${s.title}`).join('\n')}\n${credits}\n<!-- 게시 전: 원음 제3자 음악 확인 · 전체 청취 · 회원 원본 이미지로 10초 엔딩 추가 -->\n`);
write(path.join(project,'publishing/youtube.en.md'),`# ${en.title}\n\nThe same game can feel different depending on what fits on screen.\nWhat is the difference between aspect ratio, field of view (FOV), and an object's screen occupancy?\n\nWe compare 16:9 and 21:9, explore the trade-off between peripheral visibility and target size, and consider how cockpits, weapons, and UI affect readable space.\nForza Horizon 5 and DOOM are illustrative examples. The 2.5D comparisons are original diagrams, not measurements made by changing those games' camera settings.\n\nGood screen design makes the information needed for the next decision clear.\nKorean narration · Korean and English subtitles\n\n## Chapters\n${plan.scenes.map((s,i)=>`${chapter(s)} ${en.scenes[i].title}`).join('\n')}\n${credits}\n<!-- Before publication: source-audio rights review, full listening review, original-image membership outro. -->\n`);
write(path.join(project,'audio/mix-report.md'),`# 본편 v2 믹스 검수\n\n- 길이 ${plan.seconds.toFixed(3)}초, 1920×1080/60fps, ${plan.totalFrames}프레임.\n- 기존 내레이션 -16 LUFS 정규화, Discovery -28 LUFS 유지. 원음 중 BGM 추가 -3dB.\n- 게임 원음 -23 LUFS 정규화 후 덕킹, 그 뒤 **0.5배(-6.0206dB)**. 이후 재정규화 없음.\n- 원음 감쇠 테스트: ${qa.sourceGainAudit.testBeforeDb} → ${qa.sourceGainAudit.testAfterDb}dB (표시 정밀도 0.1dB).\n- 실제 최종 AAC 측정: **${qa.fullLoudness.input_i} LUFS / ${qa.fullLoudness.input_tp} dBTP**.\n- 배경 단독(게임+BGM): ${qa.backgroundLoudness.input_i} LUFS.\n- clean/자막판/편집기 M4A의 AAC 패킷 해시 동일. 브라우저 WAV는 6개 지점에서 시간 증가·비무음 신호 확인.\n- 63개 한영 큐, 동일 타임코드. 실제 글자 폭 측정, 최대 박스 폭 ${layout.maxBoxWidth}px, 최대2줄, y=970.\n- 전체 MP4 디코드 성공. 6개 씬의 예시/도식 스틸 확인. ASR 대본 문자 대응 99.5~100%, 누락/반복 문장 없음.\n- ASR·파형·수치 검사는 사람이 듣는 최종 승인과 별개. 최종 청취 및 제3자 게임 음악 권리 확인 대기.\n- 회원 원본 이미지 미확보: 10초 엔딩 미포함.\n\n정확한 값: [qa.json](../production/full-v2/qa.json), [편집기 재생](../production/full-v2/editor-playback-qa.json).\n`);
write(path.join(project,'production/PROGRESS.md'),`# 현재 상태 — 본편 v2\n\n220.467초 본편 렌더 완료. 68% 실제 게임 + 32% 자체 설명. 자동차 원음 0.5배, Discovery 연속, 한국어 내레이션.\n\n최신 네 결과물은 output/small-window-game-design/에 수집한다. 정확한 타임라인/재현 명령/검수는 full-v2/ 참조.\n\n남은 게시 요건: 원본 회원 이미지로 10초 엔딩 추가, 전체 사람 청취, 원음 제3자 음악 권리 확인. 게시 승인 상태 아님.\n`);
console.log('Verified body recorded; publishReady=false');
