// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 204.86666666666667;

export const SCENE_STARTS = [
  0.0,
  33.03333333333333,
  66.4,
  100.8,
  136.4,
  170.46666666666667,
] as const;

export const SCENE_DURATIONS = [
  33.03333333333333,
  33.36666666666667,
  34.4,
  35.6,
  34.06666666666667,
  34.4,
] as const;

export const SCENE_TITLES = [
  "입력을 받았다는 신호",
  "거절할 때는 다음 행동의 단서",
  "메뉴에서는 확인 의도를 알아보기",
  "컷신은 응답과 확정을 나누기",
  "처리 중을 완료처럼 말하지 않기",
  "필요한 곳에만 응답하기",
] as const;

export const TOTAL_FRAMES = 12292;
