// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 211.36666666666667;

export const SCENE_STARTS = [
  0.0,
  31.033333333333335,
  67.43333333333334,
  101.03333333333333,
  137.03333333333333,
  175.26666666666668,
] as const;

export const SCENE_DURATIONS = [
  31.033333333333335,
  36.4,
  33.6,
  36.0,
  38.233333333333334,
  36.1,
] as const;

export const SCENE_TITLES = [
  "심부름을 행동으로 보기",
  "가는 길에 선택이 있는가",
  "완료 뒤 무엇이 바뀌는가",
  "같은 배달, 다른 세계 상태",
  "돌아오는 길을 다시 설계하기",
  "세 질문으로 플레이를 확인하기",
] as const;

export const TOTAL_FRAMES = 12682;
