import {makeProject} from '@motion-canvas/core';
import p0 from './proof0?scene';
import p1 from './proof1?scene';
import p2 from './proof2?scene';
import p3 from './proof3?scene';
import p4 from './proof4?scene';
import p5 from './proof5?scene';
import p6 from './proof6?scene';
import p7 from './proof7?scene';
export default makeProject({scenes:[p0,p1,p2,p3,p4,p5,p6,p7]});
