import {makeProject} from '@motion-canvas/core';
import audio from './assets/final-mix-intro-v3.wav';
import intro from './intro-cats-v2/scene?scene';
import s01 from './full/scene01?scene';
import s02 from './full/scene02?scene';
import s03 from './full/scene03?scene';
import s04 from './full/scene04?scene';
import s05 from './full/scene05?scene';
import s06 from './full/scene06?scene';
export default makeProject({name:'화면 비율과 시야각 — 고양이 인트로·전체 본편',audio,scenes:[intro,s01,s02,s03,s04,s05,s06]});
