// GENERATED by qwen3-tts/build_project_timing.py — do not edit by hand.
export const NARRATION_FPS = 60;
export const TOTAL_DURATION = 220.46666666666667;

export const SCENE_STARTS = [
  0.0,
  34.733333333333334,
  74.16666666666667,
  108.73333333333333,
  142.96666666666667,
  177.36666666666667,
] as const;

export const SCENE_DURATIONS = [
  34.733333333333334,
  39.43333333333333,
  34.56666666666667,
  34.233333333333334,
  34.4,
  43.1,
] as const;

export const SCENE_TITLES = [
  "우리가 보는 건 세상의 일부",
  "화면 비율은 창의 모양이다",
  "많이 보이면 무조건 좋을까",
  "표적이 작은 것도 설계다",
  "전체 화면이 전부 플레이 공간은 아니다",
  "다음 행동이 보이는 화면",
] as const;

export const TOTAL_FRAMES = 13228;
