import {makeProject} from '@motion-canvas/core';
import scene01 from './scene01?scene';
import scene02 from './scene02?scene';
import scene03 from './scene03?scene';
import scene04 from './scene04?scene';
import scene05 from './scene05?scene';
import scene06 from './scene06?scene';
import scene07 from './scene07?scene';
import scene08 from './scene08?scene';
export default makeProject({name:'let-them-play — 2.5D design comparisons (silent)',scenes:[scene01,scene02,scene03,scene04,scene05,scene06,scene07,scene08]});
